2024-08-06 18:16:01,535 INFO    StreamThr :2098288 [internal.py:wandb_internal():86] W&B internal server running at pid: 2098288, started at: 2024-08-06 18:16:01.534878
2024-08-06 18:16:01,535 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: status
2024-08-06 18:16:01,536 INFO    WriterThread:2098288 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/run-890xsl2q.wandb
2024-08-06 18:16:01,537 DEBUG   SenderThread:2098288 [sender.py:send():382] send: header
2024-08-06 18:16:01,537 DEBUG   SenderThread:2098288 [sender.py:send():382] send: run
2024-08-06 18:16:01,694 INFO    SenderThread:2098288 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files
2024-08-06 18:16:01,695 INFO    SenderThread:2098288 [sender.py:_start_run_threads():1136] run started: 890xsl2q with start time 1722939361.53482
2024-08-06 18:16:01,701 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 18:16:01,701 DEBUG   SenderThread:2098288 [sender.py:send_request():409] send_request: check_version
2024-08-06 18:16:01,804 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 18:16:01,813 DEBUG   HandlerThread:2098288 [system_info.py:__init__():32] System info init
2024-08-06 18:16:01,813 DEBUG   HandlerThread:2098288 [system_info.py:__init__():47] System info init done
2024-08-06 18:16:01,813 INFO    HandlerThread:2098288 [system_monitor.py:start():194] Starting system monitor
2024-08-06 18:16:01,813 INFO    SystemMonitor:2098288 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 18:16:01,813 INFO    HandlerThread:2098288 [system_monitor.py:probe():214] Collecting system info
2024-08-06 18:16:01,814 INFO    SystemMonitor:2098288 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 18:16:01,814 INFO    SystemMonitor:2098288 [interfaces.py:start():190] Started disk monitoring
2024-08-06 18:16:01,815 INFO    SystemMonitor:2098288 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 18:16:01,815 INFO    SystemMonitor:2098288 [interfaces.py:start():190] Started memory monitoring
2024-08-06 18:16:01,815 INFO    SystemMonitor:2098288 [interfaces.py:start():190] Started network monitoring
2024-08-06 18:16:01,821 DEBUG   HandlerThread:2098288 [system_info.py:probe():196] Probing system
2024-08-06 18:16:01,822 DEBUG   HandlerThread:2098288 [system_info.py:_probe_git():181] Probing git
2024-08-06 18:16:01,823 DEBUG   HandlerThread:2098288 [system_info.py:_probe_git():189] Probing git done
2024-08-06 18:16:01,823 DEBUG   HandlerThread:2098288 [system_info.py:probe():244] Probing system done
2024-08-06 18:16:01,823 DEBUG   HandlerThread:2098288 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T10:16:01.821625', 'startedAt': '2024-08-06T10:16:01.529533', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2b', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1518.2723214285713, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1177.601, 'min': 800.0, 'max': 5500.0}, {'current': 3457.093, 'min': 800.0, 'max': 5500.0}, {'current': 5350.604, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3109.857, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3200.767, 'min': 800.0, 'max': 5500.0}, {'current': 4782.199, 'min': 800.0, 'max': 5500.0}, {'current': 5487.988, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 2942.076, 'min': 800.0, 'max': 5600.0}, {'current': 4843.669, 'min': 800.0, 'max': 5600.0}, {'current': 3828.876, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4678.763, 'min': 800.0, 'max': 5500.0}, {'current': 5468.005, 'min': 800.0, 'max': 5500.0}, {'current': 1112.967, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1100.312, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.36191177368164}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 18:16:01,823 INFO    HandlerThread:2098288 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 18:16:01,823 INFO    HandlerThread:2098288 [system_monitor.py:probe():227] Publishing system info
2024-08-06 18:16:01,823 DEBUG   HandlerThread:2098288 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 18:16:01,823 DEBUG   HandlerThread:2098288 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 18:16:01,823 DEBUG   HandlerThread:2098288 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 18:16:02,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/requirements.txt
2024-08-06 18:16:02,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/conda-environment.yaml
2024-08-06 18:16:03,494 DEBUG   HandlerThread:2098288 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 18:16:03,494 DEBUG   HandlerThread:2098288 [system_info.py:_save_code():90] Saving code
2024-08-06 18:16:03,495 DEBUG   HandlerThread:2098288 [system_info.py:_save_code():111] Saving code done
2024-08-06 18:16:03,495 DEBUG   HandlerThread:2098288 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 18:16:03,498 ERROR   HandlerThread:2098288 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 18:16:03,498 DEBUG   HandlerThread:2098288 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 18:16:03,498 INFO    HandlerThread:2098288 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 18:16:03,499 DEBUG   SenderThread:2098288 [sender.py:send():382] send: files
2024-08-06 18:16:03,499 INFO    SenderThread:2098288 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 18:16:03,499 INFO    SenderThread:2098288 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 18:16:03,501 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 18:16:03,502 DEBUG   SenderThread:2098288 [sender.py:send():382] send: telemetry
2024-08-06 18:16:03,542 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 18:16:03,543 DEBUG   SenderThread:2098288 [sender.py:send_request():409] send_request: stop_status
2024-08-06 18:16:03,668 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6
2024-08-06 18:16:03,668 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:03,668 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91C3902CB6F4F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:03,694 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/conda-environment.yaml
2024-08-06 18:16:03,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/wandb-metadata.json
2024-08-06 18:16:03,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/code/llama/gmm.py
2024-08-06 18:16:03,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/code
2024-08-06 18:16:03,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/code/llama
2024-08-06 18:16:03,739 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb
2024-08-06 18:16:03,739 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:03,739 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91C3904DFD388</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: config
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: metric
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: telemetry
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: metric
2024-08-06 18:16:03,780 WARNING SenderThread:2098288 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: telemetry
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: telemetry
2024-08-06 18:16:03,780 DEBUG   SenderThread:2098288 [sender.py:send():382] send: config
2024-08-06 18:16:04,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:04,852 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb
2024-08-06 18:16:04,852 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:04,852 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91C3948D15616</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:04,852 INFO    wandb-upload_1:2098288 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 18:16:04,885 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6
2024-08-06 18:16:04,885 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:04,885 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91C394B6A1084</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:04,885 INFO    wandb-upload_0:2098288 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 18:16:06,695 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:06,781 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 18:16:07,320 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6
2024-08-06 18:16:07,320 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:07,320 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91C39DC5DD26C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:07,367 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb
2024-08-06 18:16:07,367 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:07,367 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91C39DEACAFBA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:11,110 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 18:16:11,111 DEBUG   SenderThread:2098288 [sender.py:send():382] send: metric
2024-08-06 18:16:11,111 DEBUG   SenderThread:2098288 [sender.py:send():382] send: metric
2024-08-06 18:16:11,111 DEBUG   SenderThread:2098288 [sender.py:send():382] send: metric
2024-08-06 18:16:11,112 DEBUG   SenderThread:2098288 [sender.py:send():382] send: metric
2024-08-06 18:16:11,112 DEBUG   SenderThread:2098288 [sender.py:send():382] send: history
2024-08-06 18:16:11,112 DEBUG   SenderThread:2098288 [sender.py:send_request():409] send_request: summary_record
2024-08-06 18:16:11,112 INFO    SenderThread:2098288 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 18:16:11,468 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb
2024-08-06 18:16:11,468 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:11,468 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91C3AD326FAB5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:11,483 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6
2024-08-06 18:16:11,483 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:11,483 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91C3AD4884C3A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:11,696 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/wandb-summary.json
2024-08-06 18:16:12,113 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 18:16:12,696 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:13,696 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:17,114 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 18:16:18,352 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 18:16:18,353 DEBUG   SenderThread:2098288 [sender.py:send():382] send: history
2024-08-06 18:16:18,353 DEBUG   SenderThread:2098288 [sender.py:send_request():409] send_request: summary_record
2024-08-06 18:16:18,354 INFO    SenderThread:2098288 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 18:16:18,501 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 18:16:18,502 DEBUG   SenderThread:2098288 [sender.py:send_request():409] send_request: stop_status
2024-08-06 18:16:18,502 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 18:16:18,697 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/wandb-summary.json
2024-08-06 18:16:19,698 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:19,710 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=66b0d187358ddf01843d3ab56a0377a2525d6394682e9fcf19224885d2290acb
2024-08-06 18:16:19,710 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:19,710 ERROR   wandb-upload_1:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91C3CBE5AC197</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:20,698 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:21,000 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T101603Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=af174c15bf82b0d48a44ae3ac1d7ab6de8b219b308fc2dc74839f76495640fc6
2024-08-06 18:16:21,000 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 18:16:21,000 ERROR   wandb-upload_0:2098288 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/890xsl2q/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/890xsl2q/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91C3D0BBFE3A8</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 18:16:22,739 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 18:16:25,418 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 18:16:25,419 DEBUG   SenderThread:2098288 [sender.py:send():382] send: history
2024-08-06 18:16:25,419 DEBUG   SenderThread:2098288 [sender.py:send_request():409] send_request: summary_record
2024-08-06 18:16:25,419 INFO    SenderThread:2098288 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 18:16:25,699 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/wandb-summary.json
2024-08-06 18:16:27,699 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
2024-08-06 18:16:28,420 DEBUG   HandlerThread:2098288 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 18:16:28,699 INFO    Thread-12 :2098288 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_181601-890xsl2q/files/output.log
