2024-08-06 20:35:19,404 INFO    StreamThr :2158434 [internal.py:wandb_internal():86] W&B internal server running at pid: 2158434, started at: 2024-08-06 20:35:19.404480
2024-08-06 20:35:19,406 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: status
2024-08-06 20:35:19,407 INFO    WriterThread:2158434 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/run-2v4zodkg.wandb
2024-08-06 20:35:19,407 DEBUG   SenderThread:2158434 [sender.py:send():382] send: header
2024-08-06 20:35:19,407 DEBUG   SenderThread:2158434 [sender.py:send():382] send: run
2024-08-06 20:35:19,653 INFO    SenderThread:2158434 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files
2024-08-06 20:35:19,653 INFO    SenderThread:2158434 [sender.py:_start_run_threads():1136] run started: 2v4zodkg with start time 1722947719.404301
2024-08-06 20:35:19,662 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 20:35:19,662 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: check_version
2024-08-06 20:35:19,759 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 20:35:19,763 DEBUG   HandlerThread:2158434 [system_info.py:__init__():32] System info init
2024-08-06 20:35:19,763 DEBUG   HandlerThread:2158434 [system_info.py:__init__():47] System info init done
2024-08-06 20:35:19,763 INFO    HandlerThread:2158434 [system_monitor.py:start():194] Starting system monitor
2024-08-06 20:35:19,764 INFO    SystemMonitor:2158434 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 20:35:19,764 INFO    HandlerThread:2158434 [system_monitor.py:probe():214] Collecting system info
2024-08-06 20:35:19,764 INFO    SystemMonitor:2158434 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 20:35:19,765 INFO    SystemMonitor:2158434 [interfaces.py:start():190] Started disk monitoring
2024-08-06 20:35:19,766 INFO    SystemMonitor:2158434 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 20:35:19,767 INFO    SystemMonitor:2158434 [interfaces.py:start():190] Started memory monitoring
2024-08-06 20:35:19,767 INFO    SystemMonitor:2158434 [interfaces.py:start():190] Started network monitoring
2024-08-06 20:35:19,774 DEBUG   HandlerThread:2158434 [system_info.py:probe():196] Probing system
2024-08-06 20:35:19,775 DEBUG   HandlerThread:2158434 [system_info.py:_probe_git():181] Probing git
2024-08-06 20:35:19,777 DEBUG   HandlerThread:2158434 [system_info.py:_probe_git():189] Probing git done
2024-08-06 20:35:19,777 DEBUG   HandlerThread:2158434 [system_info.py:probe():244] Probing system done
2024-08-06 20:35:19,777 DEBUG   HandlerThread:2158434 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T12:35:19.774829', 'startedAt': '2024-08-06T12:35:19.402387', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/qwen2-1.5b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1600.8515, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 2566.624, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2426.915, 'min': 800.0, 'max': 5500.0}, {'current': 2357.863, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2262.449, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2541.34, 'min': 800.0, 'max': 5600.0}, {'current': 2598.448, 'min': 800.0, 'max': 5600.0}, {'current': 5283.806, 'min': 800.0, 'max': 5600.0}, {'current': 2530.568, 'min': 800.0, 'max': 5600.0}, {'current': 1391.104, 'min': 800.0, 'max': 5500.0}, {'current': 3783.671, 'min': 800.0, 'max': 5500.0}, {'current': 2390.933, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.38146591186523}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 20:35:19,777 INFO    HandlerThread:2158434 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 20:35:19,777 INFO    HandlerThread:2158434 [system_monitor.py:probe():227] Publishing system info
2024-08-06 20:35:19,777 DEBUG   HandlerThread:2158434 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 20:35:19,778 DEBUG   HandlerThread:2158434 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 20:35:19,778 DEBUG   HandlerThread:2158434 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 20:35:20,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/conda-environment.yaml
2024-08-06 20:35:20,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/requirements.txt
2024-08-06 20:35:21,469 DEBUG   HandlerThread:2158434 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 20:35:21,469 DEBUG   HandlerThread:2158434 [system_info.py:_save_code():90] Saving code
2024-08-06 20:35:21,470 DEBUG   HandlerThread:2158434 [system_info.py:_save_code():111] Saving code done
2024-08-06 20:35:21,470 DEBUG   HandlerThread:2158434 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 20:35:21,473 ERROR   HandlerThread:2158434 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 20:35:21,473 DEBUG   HandlerThread:2158434 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 20:35:21,473 INFO    HandlerThread:2158434 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 20:35:21,474 DEBUG   SenderThread:2158434 [sender.py:send():382] send: files
2024-08-06 20:35:21,474 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 20:35:21,474 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 20:35:21,476 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 20:35:21,476 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: stop_status
2024-08-06 20:35:21,477 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 20:35:21,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/conda-environment.yaml
2024-08-06 20:35:21,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-metadata.json
2024-08-06 20:35:21,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/code/llama/gmm.py
2024-08-06 20:35:21,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/code/llama
2024-08-06 20:35:21,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/code
2024-08-06 20:35:21,653 DEBUG   SenderThread:2158434 [sender.py:send():382] send: telemetry
2024-08-06 20:35:21,653 DEBUG   SenderThread:2158434 [sender.py:send():382] send: config
2024-08-06 20:35:21,654 DEBUG   SenderThread:2158434 [sender.py:send():382] send: metric
2024-08-06 20:35:21,654 DEBUG   SenderThread:2158434 [sender.py:send():382] send: telemetry
2024-08-06 20:35:21,654 DEBUG   SenderThread:2158434 [sender.py:send():382] send: metric
2024-08-06 20:35:21,654 WARNING SenderThread:2158434 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 20:35:21,654 DEBUG   SenderThread:2158434 [sender.py:send():382] send: telemetry
2024-08-06 20:35:21,654 DEBUG   SenderThread:2158434 [sender.py:send():382] send: telemetry
2024-08-06 20:35:21,654 DEBUG   SenderThread:2158434 [sender.py:send():382] send: config
2024-08-06 20:35:21,790 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69
2024-08-06 20:35:21,790 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5175', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:21,790 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923D309DFFE70</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:21,799 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020
2024-08-06 20:35:21,799 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:21,799 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923D3078A19F9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:22,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:22,921 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020
2024-08-06 20:35:22,921 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:22,921 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923D34C8B87AF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:22,921 INFO    wandb-upload_1:2158434 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 20:35:22,947 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69
2024-08-06 20:35:22,947 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5175', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:22,947 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923D34EE67F5B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:22,947 INFO    wandb-upload_0:2158434 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 20:35:23,607 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:35:23,608 DEBUG   SenderThread:2158434 [sender.py:send():382] send: metric
2024-08-06 20:35:23,608 DEBUG   SenderThread:2158434 [sender.py:send():382] send: metric
2024-08-06 20:35:23,608 DEBUG   SenderThread:2158434 [sender.py:send():382] send: metric
2024-08-06 20:35:23,608 DEBUG   SenderThread:2158434 [sender.py:send():382] send: metric
2024-08-06 20:35:23,608 DEBUG   SenderThread:2158434 [sender.py:send():382] send: history
2024-08-06 20:35:23,608 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:35:23,609 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:35:23,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-summary.json
2024-08-06 20:35:24,610 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 20:35:24,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:25,025 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69
2024-08-06 20:35:25,025 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5175', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:25,025 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923D3CA96E7C4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:25,064 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020
2024-08-06 20:35:25,064 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:25,064 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923D3CBC0BDDA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:25,407 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:35:25,407 DEBUG   SenderThread:2158434 [sender.py:send():382] send: history
2024-08-06 20:35:25,407 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:35:25,408 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:35:25,653 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-summary.json
2024-08-06 20:35:25,654 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:26,654 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:27,084 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:35:27,084 DEBUG   SenderThread:2158434 [sender.py:send():382] send: history
2024-08-06 20:35:27,085 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:35:27,085 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:35:27,654 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-summary.json
2024-08-06 20:35:27,654 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:28,654 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:28,902 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:35:28,902 DEBUG   SenderThread:2158434 [sender.py:send():382] send: history
2024-08-06 20:35:28,903 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:35:28,903 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:35:29,520 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f213a52cde9b68f76368df42bc6c50984885f330f6d7bebd2dce05358cd1cf69
2024-08-06 20:35:29,520 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5175', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:29,520 ERROR   wandb-upload_0:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923D4D69A89E3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:29,654 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-summary.json
2024-08-06 20:35:29,655 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:29,903 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 20:35:29,909 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52dcb6cad1c194b8faedb3c8f1d56f957f5af027902521fb3fda9b129b641020
2024-08-06 20:35:29,909 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:29,909 ERROR   wandb-upload_1:2158434 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/2v4zodkg/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/2v4zodkg/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923D4EC93CA12</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:30,655 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:30,673 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:35:30,674 DEBUG   SenderThread:2158434 [sender.py:send():382] send: history
2024-08-06 20:35:30,674 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:35:30,674 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:35:31,655 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-summary.json
2024-08-06 20:35:31,655 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
2024-08-06 20:35:32,434 DEBUG   HandlerThread:2158434 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:35:32,434 DEBUG   SenderThread:2158434 [sender.py:send():382] send: history
2024-08-06 20:35:32,434 DEBUG   SenderThread:2158434 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:35:32,434 INFO    SenderThread:2158434 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:35:32,655 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/wandb-summary.json
2024-08-06 20:35:32,655 INFO    Thread-12 :2158434 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203519-2v4zodkg/files/output.log
