2024-08-08 17:25:14,317 INFO    StreamThr :294444 [internal.py:wandb_internal():86] W&B internal server running at pid: 294444, started at: 2024-08-08 17:25:14.317613
2024-08-08 17:25:14,319 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: status
2024-08-08 17:25:14,319 INFO    WriterThread:294444 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/run-arubpqj9.wandb
2024-08-08 17:25:14,319 DEBUG   SenderThread:294444 [sender.py:send():382] send: header
2024-08-08 17:25:14,346 DEBUG   SenderThread:294444 [sender.py:send():382] send: run
2024-08-08 17:25:14,601 INFO    SenderThread:294444 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files
2024-08-08 17:25:14,601 INFO    SenderThread:294444 [sender.py:_start_run_threads():1136] run started: arubpqj9 with start time 1723109114.317603
2024-08-08 17:25:14,607 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 17:25:14,607 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: check_version
2024-08-08 17:25:14,712 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 17:25:14,721 DEBUG   HandlerThread:294444 [system_info.py:__init__():32] System info init
2024-08-08 17:25:14,721 DEBUG   HandlerThread:294444 [system_info.py:__init__():47] System info init done
2024-08-08 17:25:14,721 INFO    HandlerThread:294444 [system_monitor.py:start():194] Starting system monitor
2024-08-08 17:25:14,722 INFO    SystemMonitor:294444 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 17:25:14,722 INFO    SystemMonitor:294444 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 17:25:14,722 INFO    HandlerThread:294444 [system_monitor.py:probe():214] Collecting system info
2024-08-08 17:25:14,722 INFO    SystemMonitor:294444 [interfaces.py:start():190] Started disk monitoring
2024-08-08 17:25:14,723 INFO    SystemMonitor:294444 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 17:25:14,723 INFO    SystemMonitor:294444 [interfaces.py:start():190] Started memory monitoring
2024-08-08 17:25:14,723 INFO    SystemMonitor:294444 [interfaces.py:start():190] Started network monitoring
2024-08-08 17:25:14,729 DEBUG   HandlerThread:294444 [system_info.py:probe():196] Probing system
2024-08-08 17:25:14,730 DEBUG   HandlerThread:294444 [system_info.py:_probe_git():181] Probing git
2024-08-08 17:25:14,734 DEBUG   HandlerThread:294444 [system_info.py:_probe_git():189] Probing git done
2024-08-08 17:25:14,734 DEBUG   HandlerThread:294444 [system_info.py:probe():244] Probing system done
2024-08-08 17:25:14,734 DEBUG   HandlerThread:294444 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T09:25:14.729518', 'startedAt': '2024-08-08T09:25:14.312224', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2156.237071428571, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 5434.147, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5374.618, 'min': 800.0, 'max': 5500.0}, {'current': 2791.307, 'min': 800.0, 'max': 5500.0}, {'current': 5453.44, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5260.951, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 3833.798, 'min': 800.0, 'max': 5600.0}, {'current': 5147.401, 'min': 800.0, 'max': 5600.0}, {'current': 1468.732, 'min': 800.0, 'max': 5600.0}, {'current': 5154.148, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4771.543, 'min': 800.0, 'max': 5500.0}, {'current': 1358.479, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1526.074, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0224151611328}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 17:25:14,734 INFO    HandlerThread:294444 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 17:25:14,734 INFO    HandlerThread:294444 [system_monitor.py:probe():227] Publishing system info
2024-08-08 17:25:14,734 DEBUG   HandlerThread:294444 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 17:25:14,734 DEBUG   HandlerThread:294444 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 17:25:14,734 DEBUG   HandlerThread:294444 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 17:25:15,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/conda-environment.yaml
2024-08-08 17:25:15,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/requirements.txt
2024-08-08 17:25:16,417 DEBUG   HandlerThread:294444 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 17:25:16,417 DEBUG   HandlerThread:294444 [system_info.py:_save_code():90] Saving code
2024-08-08 17:25:16,419 DEBUG   HandlerThread:294444 [system_info.py:_save_code():111] Saving code done
2024-08-08 17:25:16,419 DEBUG   HandlerThread:294444 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 17:25:16,457 DEBUG   HandlerThread:294444 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 17:25:16,458 INFO    HandlerThread:294444 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 17:25:16,460 DEBUG   SenderThread:294444 [sender.py:send():382] send: files
2024-08-08 17:25:16,461 INFO    SenderThread:294444 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 17:25:16,461 INFO    SenderThread:294444 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 17:25:16,461 INFO    SenderThread:294444 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 17:25:16,468 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 17:25:16,469 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: stop_status
2024-08-08 17:25:16,476 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 17:25:16,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/conda-environment.yaml
2024-08-08 17:25:16,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/wandb-metadata.json
2024-08-08 17:25:16,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/diff.patch
2024-08-08 17:25:16,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/code/llama/gmm.py
2024-08-08 17:25:16,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/code/llama
2024-08-08 17:25:16,601 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/code
2024-08-08 17:25:16,826 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946
2024-08-08 17:25:16,826 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:16,826 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B69CBB50C766</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:17,130 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073
2024-08-08 17:25:17,130 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291447', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:17,130 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B69CBAEB68A1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:17,223 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c
2024-08-08 17:25:17,224 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:17,224 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B69CC22FA6EA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:17,721 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 17:25:17,744 DEBUG   SenderThread:294444 [sender.py:send():382] send: telemetry
2024-08-08 17:25:17,744 DEBUG   SenderThread:294444 [sender.py:send():382] send: config
2024-08-08 17:25:17,745 DEBUG   SenderThread:294444 [sender.py:send():382] send: metric
2024-08-08 17:25:17,745 DEBUG   SenderThread:294444 [sender.py:send():382] send: telemetry
2024-08-08 17:25:17,745 DEBUG   SenderThread:294444 [sender.py:send():382] send: metric
2024-08-08 17:25:17,746 WARNING SenderThread:294444 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 17:25:17,746 DEBUG   SenderThread:294444 [sender.py:send():382] send: telemetry
2024-08-08 17:25:17,746 DEBUG   SenderThread:294444 [sender.py:send():382] send: telemetry
2024-08-08 17:25:17,746 DEBUG   SenderThread:294444 [sender.py:send():382] send: config
2024-08-08 17:25:17,749 DEBUG   SenderThread:294444 [sender.py:send():382] send: exit
2024-08-08 17:25:17,749 INFO    SenderThread:294444 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 17:25:17,749 INFO    SenderThread:294444 [sender.py:send_exit():591] handling runtime: 2
2024-08-08 17:25:17,751 INFO    SenderThread:294444 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:25:17,752 INFO    SenderThread:294444 [sender.py:send_exit():597] send defer
2024-08-08 17:25:17,752 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 17:25:17,753 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,753 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 17:25:17,753 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,754 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 17:25:17,754 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 1
2024-08-08 17:25:17,754 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,754 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 17:25:17,754 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,755 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 17:25:17,755 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 2
2024-08-08 17:25:17,755 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,755 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 17:25:17,755 INFO    HandlerThread:294444 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 17:25:17,756 DEBUG   SystemMonitor:294444 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 17:25:17,756 DEBUG   SystemMonitor:294444 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 17:25:17,756 DEBUG   SystemMonitor:294444 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 17:25:17,757 INFO    HandlerThread:294444 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 17:25:17,758 INFO    HandlerThread:294444 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 17:25:17,789 INFO    HandlerThread:294444 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 17:25:17,789 INFO    HandlerThread:294444 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 17:25:17,789 INFO    HandlerThread:294444 [interfaces.py:finish():202] Joined network monitor
2024-08-08 17:25:17,789 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,789 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 17:25:17,789 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 3
2024-08-08 17:25:17,789 DEBUG   SenderThread:294444 [sender.py:send():382] send: stats
2024-08-08 17:25:17,789 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,789 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 17:25:17,790 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 4
2024-08-08 17:25:17,790 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,790 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 17:25:17,790 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 5
2024-08-08 17:25:17,790 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,790 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 17:25:17,790 DEBUG   SenderThread:294444 [sender.py:send():382] send: summary
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:25:17,790 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 6
2024-08-08 17:25:17,790 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,790 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 17:25:17,790 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,790 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 17:25:17,792 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 17:25:17,983 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 7
2024-08-08 17:25:17,983 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:17,983 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 17:25:17,983 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:17,983 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 17:25:18,027 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946
2024-08-08 17:25:18,027 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:18,027 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B69D05ECEB17</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:18,329 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c
2024-08-08 17:25:18,329 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:18,330 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B69D18DDAEFC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:18,330 INFO    wandb-upload_0:294444 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:25:18,602 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/config.yaml
2024-08-08 17:25:18,603 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/output.log
2024-08-08 17:25:18,603 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/wandb-summary.json
2024-08-08 17:25:18,722 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 17:25:19,181 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073
2024-08-08 17:25:19,182 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291447', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:19,182 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B69D1FA462E1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:19,761 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 8
2024-08-08 17:25:19,761 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 17:25:19,762 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:19,762 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 17:25:19,762 DEBUG   SenderThread:294444 [sender.py:send_request():409] send_request: defer
2024-08-08 17:25:19,762 INFO    SenderThread:294444 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 17:25:19,762 INFO    SenderThread:294444 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 17:25:19,763 INFO    SenderThread:294444 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 17:25:19,781 INFO    SenderThread:294444 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 17:25:19,793 INFO    SenderThread:294444 [sender.py:transition_state():617] send defer: 9
2024-08-08 17:25:19,793 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:25:19,793 INFO    HandlerThread:294444 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 17:25:19,793 DEBUG   SenderThread:294444 [sender.py:send():382] send: artifact
2024-08-08 17:25:20,377 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684
2024-08-08 17:25:20,377 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:20,378 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B69D93627788</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:20,429 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987
2024-08-08 17:25:20,429 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:20,429 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B69D934B48F6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:20,555 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c
2024-08-08 17:25:20,556 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:20,556 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B69D9DC0E14B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:20,603 INFO    Thread-12 :294444 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172514-arubpqj9/files/output.log
2024-08-08 17:25:20,660 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946
2024-08-08 17:25:20,661 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:20,661 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B69D9DFA7359</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:21,537 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987
2024-08-08 17:25:21,537 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:21,537 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B69DD713D26E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:21,568 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073
2024-08-08 17:25:21,568 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291447', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:21,568 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B69DD7E387D6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:21,646 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684
2024-08-08 17:25:21,646 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:21,646 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B69DDEE9417B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:23,725 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 17:25:23,950 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987
2024-08-08 17:25:23,950 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:23,950 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B69E670160AE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:23,950 INFO    wandb-upload_4:294444 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:25:24,159 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684
2024-08-08 17:25:24,159 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:24,159 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B69E74A3F7C9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:24,159 INFO    wandb-upload_3:294444 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:25:24,866 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946
2024-08-08 17:25:24,866 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:24,873 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B69E9EA9AE77</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:25,561 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c
2024-08-08 17:25:25,561 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:25,561 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B69EC81DAB57</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:26,022 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073
2024-08-08 17:25:26,022 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291447', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:26,022 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B69EDCB75C1D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:28,267 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684
2024-08-08 17:25:28,267 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:28,267 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B69F6972ADE7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:28,668 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987
2024-08-08 17:25:28,668 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:28,668 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B69F803C92D9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:28,728 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 17:25:33,680 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=836f19b4bbc341dd572a742f642569c2860fac23f67dac0b14e89b51be958946
2024-08-08 17:25:33,680 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:33,680 ERROR   wandb-upload_1:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B6A0AC035FCF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:33,730 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 17:25:34,851 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=910322b91b677738675a18340b801e6161feaed41fdbcb650fd229fe8978014c
2024-08-08 17:25:34,851 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:34,851 ERROR   wandb-upload_0:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B6A0F1CACAE3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:35,839 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/arubpqj9/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092516Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a1cef1bf7777603dfeeae99e7b0e2d5dc0f291f136859490ba5754ecd160b073
2024-08-08 17:25:35,840 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291447', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:35,840 ERROR   wandb-upload_2:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/arubpqj9/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/arubpqj9/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B6A126EFDB90</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:36,836 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=9364b28bddddff6bfa7ca0de4dc242562a54ad515cff01b349b425b9f8d55987
2024-08-08 17:25:36,836 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:36,836 ERROR   wandb-upload_4:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B6A16712DCE7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:38,162 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092520Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0fd7e6763a4713bd4282d486095a26f310be07adbc108c2d62e9a6653b6e684
2024-08-08 17:25:38,162 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:25:38,162 ERROR   wandb-upload_3:294444 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/525/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B6A1B73EA9E1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:25:38,733 DEBUG   HandlerThread:294444 [handler.py:handle_request():146] handle_request: keepalive
