2024-08-08 17:23:28,072 INFO    StreamThr :292967 [internal.py:wandb_internal():86] W&B internal server running at pid: 292967, started at: 2024-08-08 17:23:28.071882
2024-08-08 17:23:28,073 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: status
2024-08-08 17:23:28,073 INFO    WriterThread:292967 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/run-ledk4wj5.wandb
2024-08-08 17:23:28,074 DEBUG   SenderThread:292967 [sender.py:send():382] send: header
2024-08-08 17:23:28,110 DEBUG   SenderThread:292967 [sender.py:send():382] send: run
2024-08-08 17:23:28,348 INFO    SenderThread:292967 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files
2024-08-08 17:23:28,348 INFO    SenderThread:292967 [sender.py:_start_run_threads():1136] run started: ledk4wj5 with start time 1723109008.071845
2024-08-08 17:23:28,364 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 17:23:28,364 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: check_version
2024-08-08 17:23:28,476 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 17:23:28,484 DEBUG   HandlerThread:292967 [system_info.py:__init__():32] System info init
2024-08-08 17:23:28,484 DEBUG   HandlerThread:292967 [system_info.py:__init__():47] System info init done
2024-08-08 17:23:28,484 INFO    HandlerThread:292967 [system_monitor.py:start():194] Starting system monitor
2024-08-08 17:23:28,484 INFO    SystemMonitor:292967 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 17:23:28,485 INFO    SystemMonitor:292967 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 17:23:28,485 INFO    HandlerThread:292967 [system_monitor.py:probe():214] Collecting system info
2024-08-08 17:23:28,485 INFO    SystemMonitor:292967 [interfaces.py:start():190] Started disk monitoring
2024-08-08 17:23:28,486 INFO    SystemMonitor:292967 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 17:23:28,486 INFO    SystemMonitor:292967 [interfaces.py:start():190] Started memory monitoring
2024-08-08 17:23:28,486 INFO    SystemMonitor:292967 [interfaces.py:start():190] Started network monitoring
2024-08-08 17:23:28,492 DEBUG   HandlerThread:292967 [system_info.py:probe():196] Probing system
2024-08-08 17:23:28,494 DEBUG   HandlerThread:292967 [system_info.py:_probe_git():181] Probing git
2024-08-08 17:23:28,497 DEBUG   HandlerThread:292967 [system_info.py:_probe_git():189] Probing git done
2024-08-08 17:23:28,497 DEBUG   HandlerThread:292967 [system_info.py:probe():244] Probing system done
2024-08-08 17:23:28,498 DEBUG   HandlerThread:292967 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T09:23:28.492834', 'startedAt': '2024-08-08T09:23:28.066675', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt', '--gradient_checkpointing', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1251.4075714285714, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 1099.729, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 3296.112, 'min': 800.0, 'max': 5500.0}, {'current': 3273.714, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 4592.005, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4299.697, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1187.466, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0198402404785}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 17:23:28,498 INFO    HandlerThread:292967 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 17:23:28,498 INFO    HandlerThread:292967 [system_monitor.py:probe():227] Publishing system info
2024-08-08 17:23:28,498 DEBUG   HandlerThread:292967 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 17:23:28,498 DEBUG   HandlerThread:292967 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 17:23:28,498 DEBUG   HandlerThread:292967 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 17:23:29,349 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/requirements.txt
2024-08-08 17:23:29,349 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/conda-environment.yaml
2024-08-08 17:23:30,159 DEBUG   HandlerThread:292967 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 17:23:30,160 DEBUG   HandlerThread:292967 [system_info.py:_save_code():90] Saving code
2024-08-08 17:23:30,161 DEBUG   HandlerThread:292967 [system_info.py:_save_code():111] Saving code done
2024-08-08 17:23:30,161 DEBUG   HandlerThread:292967 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 17:23:30,182 DEBUG   HandlerThread:292967 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 17:23:30,183 INFO    HandlerThread:292967 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 17:23:30,184 DEBUG   SenderThread:292967 [sender.py:send():382] send: files
2024-08-08 17:23:30,184 INFO    SenderThread:292967 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 17:23:30,184 INFO    SenderThread:292967 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 17:23:30,184 INFO    SenderThread:292967 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 17:23:30,187 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 17:23:30,188 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: stop_status
2024-08-08 17:23:30,189 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 17:23:30,348 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/conda-environment.yaml
2024-08-08 17:23:30,348 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/wandb-metadata.json
2024-08-08 17:23:30,348 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/diff.patch
2024-08-08 17:23:30,348 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/code/llama/gmm.py
2024-08-08 17:23:30,349 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/code
2024-08-08 17:23:30,349 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/code/llama
2024-08-08 17:23:30,425 DEBUG   SenderThread:292967 [sender.py:send():382] send: telemetry
2024-08-08 17:23:30,425 DEBUG   SenderThread:292967 [sender.py:send():382] send: config
2024-08-08 17:23:30,426 DEBUG   SenderThread:292967 [sender.py:send():382] send: metric
2024-08-08 17:23:30,426 DEBUG   SenderThread:292967 [sender.py:send():382] send: telemetry
2024-08-08 17:23:30,426 DEBUG   SenderThread:292967 [sender.py:send():382] send: metric
2024-08-08 17:23:30,426 WARNING SenderThread:292967 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 17:23:30,426 DEBUG   SenderThread:292967 [sender.py:send():382] send: telemetry
2024-08-08 17:23:30,426 DEBUG   SenderThread:292967 [sender.py:send():382] send: telemetry
2024-08-08 17:23:30,426 DEBUG   SenderThread:292967 [sender.py:send():382] send: config
2024-08-08 17:23:30,476 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933
2024-08-08 17:23:30,476 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5296', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:30,476 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B683FCBDD403</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:30,629 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822
2024-08-08 17:23:30,629 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:30,629 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B68401CC56F1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:30,681 DEBUG   SenderThread:292967 [sender.py:send():382] send: exit
2024-08-08 17:23:30,681 INFO    SenderThread:292967 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 17:23:30,682 INFO    SenderThread:292967 [sender.py:send_exit():591] handling runtime: 2
2024-08-08 17:23:30,684 INFO    SenderThread:292967 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:23:30,684 INFO    SenderThread:292967 [sender.py:send_exit():597] send defer
2024-08-08 17:23:30,684 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,685 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 17:23:30,685 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,685 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 17:23:30,685 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 1
2024-08-08 17:23:30,685 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,686 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 17:23:30,686 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,686 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 17:23:30,686 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 2
2024-08-08 17:23:30,686 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,686 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 17:23:30,686 INFO    HandlerThread:292967 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 17:23:30,686 DEBUG   SystemMonitor:292967 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 17:23:30,687 INFO    HandlerThread:292967 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 17:23:30,687 DEBUG   SystemMonitor:292967 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 17:23:30,688 INFO    HandlerThread:292967 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 17:23:30,688 DEBUG   SystemMonitor:292967 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 17:23:30,696 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af
2024-08-08 17:23:30,696 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291348', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:30,696 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B683FD7D3449</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:30,734 INFO    HandlerThread:292967 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 17:23:30,734 INFO    HandlerThread:292967 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 17:23:30,734 INFO    HandlerThread:292967 [interfaces.py:finish():202] Joined network monitor
2024-08-08 17:23:30,734 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,734 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 17:23:30,734 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 3
2024-08-08 17:23:30,734 DEBUG   SenderThread:292967 [sender.py:send():382] send: stats
2024-08-08 17:23:30,734 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,734 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 17:23:30,734 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,734 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 17:23:30,734 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 4
2024-08-08 17:23:30,734 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,734 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 17:23:30,735 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,735 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 17:23:30,735 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 5
2024-08-08 17:23:30,735 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,735 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 17:23:30,735 DEBUG   SenderThread:292967 [sender.py:send():382] send: summary
2024-08-08 17:23:30,735 INFO    SenderThread:292967 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:23:30,735 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,735 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 17:23:30,735 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 6
2024-08-08 17:23:30,735 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,735 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 17:23:30,735 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,735 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 17:23:30,737 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 17:23:30,838 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 7
2024-08-08 17:23:30,838 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:30,838 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 17:23:30,838 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:30,838 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 17:23:31,349 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/config.yaml
2024-08-08 17:23:31,350 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/wandb-summary.json
2024-08-08 17:23:31,350 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/output.log
2024-08-08 17:23:31,681 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 17:23:31,734 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933
2024-08-08 17:23:31,734 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5296', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:31,734 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B684478BCE04</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:31,734 INFO    wandb-upload_0:292967 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:23:31,817 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822
2024-08-08 17:23:31,817 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:31,817 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B6844C852347</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:32,111 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af
2024-08-08 17:23:32,111 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291348', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:32,111 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B6844AAE69FE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:32,437 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 8
2024-08-08 17:23:32,437 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 17:23:32,437 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:32,438 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 17:23:32,438 DEBUG   SenderThread:292967 [sender.py:send_request():409] send_request: defer
2024-08-08 17:23:32,438 INFO    SenderThread:292967 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 17:23:32,438 INFO    SenderThread:292967 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 17:23:32,438 INFO    SenderThread:292967 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 17:23:32,454 INFO    SenderThread:292967 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 17:23:32,459 INFO    SenderThread:292967 [sender.py:transition_state():617] send defer: 9
2024-08-08 17:23:32,459 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: defer
2024-08-08 17:23:32,459 INFO    HandlerThread:292967 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 17:23:32,459 DEBUG   SenderThread:292967 [sender.py:send():382] send: artifact
2024-08-08 17:23:32,681 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 17:23:33,100 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b
2024-08-08 17:23:33,100 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:33,100 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B6849922B0BB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:33,338 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4
2024-08-08 17:23:33,338 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:33,338 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B6849CE22191</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:33,351 INFO    Thread-12 :292967 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_172328-ledk4wj5/files/output.log
2024-08-08 17:23:33,827 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933
2024-08-08 17:23:33,827 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5296', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:33,827 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B684C4526370</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:34,098 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822
2024-08-08 17:23:34,098 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:34,098 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B684D4572C56</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:34,349 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b
2024-08-08 17:23:34,349 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:34,349 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B684E3A709C5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:34,420 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af
2024-08-08 17:23:34,420 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291348', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:34,420 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B684DCFEB8BE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:34,601 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4
2024-08-08 17:23:34,602 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:34,602 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B684ECCCDF65</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:36,618 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b
2024-08-08 17:23:36,618 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:36,618 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B6856AB84C93</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:36,618 INFO    wandb-upload_3:292967 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:23:37,231 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4
2024-08-08 17:23:37,231 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:37,231 ERROR   wandb-upload_4:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9B6858492FBE9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:37,231 INFO    wandb-upload_4:292967 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=5278ef3ff55860ec05576feebb9ed1f20d6ab372149affc4e303511cea2e8de4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:23:37,684 DEBUG   HandlerThread:292967 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 17:23:38,538 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=dd51766c3a1e0fabfd0425c9d866c39f7f660bac73944fe2ae834ec55bcf2933
2024-08-08 17:23:38,538 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5296', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:38,539 ERROR   wandb-upload_0:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B685DD0D855B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:38,740 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e20a89a3f8418b72cdc0eb809d2ff8b506a0d6f91e8117f32428d76c998f822
2024-08-08 17:23:38,740 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:38,740 ERROR   wandb-upload_1:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B685E9137077</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:39,326 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/ledk4wj5/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092330Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba06e80d230271b494562f5305ff951de44919f10f13c17ad3dfb035f4b9b5af
2024-08-08 17:23:39,326 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291348', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:39,326 ERROR   wandb-upload_2:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/ledk4wj5/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/ledk4wj5/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B686098A2C6D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:23:40,847 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T092332Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=fda570ca57da4bac2cf1622a716858b98391525193bd7d5dd6bd260040ec699b
2024-08-08 17:23:40,847 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:23:40,847 ERROR   wandb-upload_3:292967 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/523/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B68666C3CF09</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
