2024-08-06 19:59:48,151 INFO    StreamThr :2147087 [internal.py:wandb_internal():86] W&B internal server running at pid: 2147087, started at: 2024-08-06 19:59:48.151090
2024-08-06 19:59:48,152 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: status
2024-08-06 19:59:48,153 INFO    WriterThread:2147087 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/run-184enav0.wandb
2024-08-06 19:59:48,153 DEBUG   SenderThread:2147087 [sender.py:send():382] send: header
2024-08-06 19:59:48,153 DEBUG   SenderThread:2147087 [sender.py:send():382] send: run
2024-08-06 19:59:48,390 INFO    SenderThread:2147087 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files
2024-08-06 19:59:48,390 INFO    SenderThread:2147087 [sender.py:_start_run_threads():1136] run started: 184enav0 with start time 1722945588.151019
2024-08-06 19:59:48,397 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 19:59:48,397 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: check_version
2024-08-06 19:59:48,486 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 19:59:48,495 DEBUG   HandlerThread:2147087 [system_info.py:__init__():32] System info init
2024-08-06 19:59:48,495 DEBUG   HandlerThread:2147087 [system_info.py:__init__():47] System info init done
2024-08-06 19:59:48,495 INFO    HandlerThread:2147087 [system_monitor.py:start():194] Starting system monitor
2024-08-06 19:59:48,495 INFO    SystemMonitor:2147087 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 19:59:48,495 INFO    HandlerThread:2147087 [system_monitor.py:probe():214] Collecting system info
2024-08-06 19:59:48,495 INFO    SystemMonitor:2147087 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 19:59:48,496 INFO    SystemMonitor:2147087 [interfaces.py:start():190] Started disk monitoring
2024-08-06 19:59:48,496 INFO    SystemMonitor:2147087 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 19:59:48,496 INFO    SystemMonitor:2147087 [interfaces.py:start():190] Started memory monitoring
2024-08-06 19:59:48,496 INFO    SystemMonitor:2147087 [interfaces.py:start():190] Started network monitoring
2024-08-06 19:59:48,505 DEBUG   HandlerThread:2147087 [system_info.py:probe():196] Probing system
2024-08-06 19:59:48,507 DEBUG   HandlerThread:2147087 [system_info.py:_probe_git():181] Probing git
2024-08-06 19:59:48,509 DEBUG   HandlerThread:2147087 [system_info.py:_probe_git():189] Probing git done
2024-08-06 19:59:48,510 DEBUG   HandlerThread:2147087 [system_info.py:probe():244] Probing system done
2024-08-06 19:59:48,510 DEBUG   HandlerThread:2147087 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T11:59:48.506059', 'startedAt': '2024-08-06T11:59:48.146494', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/qwen2-1.5b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2164.80375, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5420.053, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 4286.294, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4305.115, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 4299.985, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.3749198913574}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 19:59:48,510 INFO    HandlerThread:2147087 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 19:59:48,510 INFO    HandlerThread:2147087 [system_monitor.py:probe():227] Publishing system info
2024-08-06 19:59:48,510 DEBUG   HandlerThread:2147087 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 19:59:48,510 DEBUG   HandlerThread:2147087 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 19:59:48,510 DEBUG   HandlerThread:2147087 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 19:59:49,390 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/requirements.txt
2024-08-06 19:59:49,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/conda-environment.yaml
2024-08-06 19:59:50,179 DEBUG   HandlerThread:2147087 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 19:59:50,179 DEBUG   HandlerThread:2147087 [system_info.py:_save_code():90] Saving code
2024-08-06 19:59:50,181 DEBUG   HandlerThread:2147087 [system_info.py:_save_code():111] Saving code done
2024-08-06 19:59:50,181 DEBUG   HandlerThread:2147087 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 19:59:50,184 ERROR   HandlerThread:2147087 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 19:59:50,184 DEBUG   HandlerThread:2147087 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 19:59:50,184 INFO    HandlerThread:2147087 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 19:59:50,185 DEBUG   SenderThread:2147087 [sender.py:send():382] send: files
2024-08-06 19:59:50,185 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 19:59:50,185 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 19:59:50,187 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:59:50,187 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:59:50,187 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:59:50,390 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/conda-environment.yaml
2024-08-06 19:59:50,390 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/code/llama/gmm.py
2024-08-06 19:59:50,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-metadata.json
2024-08-06 19:59:50,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/code
2024-08-06 19:59:50,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/code/llama
2024-08-06 19:59:50,433 DEBUG   SenderThread:2147087 [sender.py:send():382] send: telemetry
2024-08-06 19:59:50,433 DEBUG   SenderThread:2147087 [sender.py:send():382] send: config
2024-08-06 19:59:50,434 DEBUG   SenderThread:2147087 [sender.py:send():382] send: metric
2024-08-06 19:59:50,434 DEBUG   SenderThread:2147087 [sender.py:send():382] send: telemetry
2024-08-06 19:59:50,434 DEBUG   SenderThread:2147087 [sender.py:send():382] send: metric
2024-08-06 19:59:50,434 WARNING SenderThread:2147087 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 19:59:50,434 DEBUG   SenderThread:2147087 [sender.py:send():382] send: telemetry
2024-08-06 19:59:50,434 DEBUG   SenderThread:2147087 [sender.py:send():382] send: telemetry
2024-08-06 19:59:50,434 DEBUG   SenderThread:2147087 [sender.py:send():382] send: config
2024-08-06 19:59:50,448 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc
2024-08-06 19:59:50,448 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5161', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:50,448 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921E2CC838557</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:50,470 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659
2024-08-06 19:59:50,470 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:50,470 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E921E2CB164007</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:51,390 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:51,676 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659
2024-08-06 19:59:51,677 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:51,677 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E921E315294F22</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:51,677 INFO    wandb-upload_1:2147087 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:59:51,703 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc
2024-08-06 19:59:51,703 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5161', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:51,704 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921E3174F665A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:51,704 INFO    wandb-upload_0:2147087 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:59:52,047 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:59:52,048 DEBUG   SenderThread:2147087 [sender.py:send():382] send: metric
2024-08-06 19:59:52,048 DEBUG   SenderThread:2147087 [sender.py:send():382] send: metric
2024-08-06 19:59:52,048 DEBUG   SenderThread:2147087 [sender.py:send():382] send: metric
2024-08-06 19:59:52,048 DEBUG   SenderThread:2147087 [sender.py:send():382] send: metric
2024-08-06 19:59:52,048 DEBUG   SenderThread:2147087 [sender.py:send():382] send: history
2024-08-06 19:59:52,048 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:59:52,049 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:59:52,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-summary.json
2024-08-06 19:59:53,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:53,613 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:59:53,614 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:59:53,614 DEBUG   SenderThread:2147087 [sender.py:send():382] send: history
2024-08-06 19:59:53,614 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:59:53,614 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:59:54,182 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc
2024-08-06 19:59:54,182 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5161', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:54,182 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921E3AB13D108</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:54,199 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659
2024-08-06 19:59:54,199 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:54,199 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E921E3AB3EC1F4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:54,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:54,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-summary.json
2024-08-06 19:59:55,045 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:59:55,045 DEBUG   SenderThread:2147087 [sender.py:send():382] send: history
2024-08-06 19:59:55,045 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:59:55,045 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:59:55,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:55,391 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-summary.json
2024-08-06 19:59:56,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:56,623 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:59:56,624 DEBUG   SenderThread:2147087 [sender.py:send():382] send: history
2024-08-06 19:59:56,624 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:59:56,624 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:59:57,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:57,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-summary.json
2024-08-06 19:59:58,162 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:59:58,163 DEBUG   SenderThread:2147087 [sender.py:send():382] send: history
2024-08-06 19:59:58,163 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:59:58,163 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:59:58,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:58,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-summary.json
2024-08-06 19:59:58,565 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5c837946a8eaa87125cd4617d7e437c81dda84ba298295c8ea65244ddc48bbc
2024-08-06 19:59:58,565 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5161', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:58,565 ERROR   wandb-upload_0:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921E4B00EC097</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:59,026 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/184enav0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115950Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1af29dd97450f835ba631d1b36c574ffdc81534bd262a5ebd403b06cba73e659
2024-08-06 19:59:59,026 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:59:59,026 ERROR   wandb-upload_1:2147087 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/184enav0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/184enav0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E921E4CAF370C3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:59:59,164 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:59:59,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 19:59:59,690 DEBUG   HandlerThread:2147087 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:59:59,690 DEBUG   SenderThread:2147087 [sender.py:send():382] send: history
2024-08-06 19:59:59,691 DEBUG   SenderThread:2147087 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:59:59,691 INFO    SenderThread:2147087 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:00:00,392 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/output.log
2024-08-06 20:00:00,393 INFO    Thread-12 :2147087 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195948-184enav0/files/wandb-summary.json
