2024-08-07 18:46:08,189 INFO    StreamThr :36244 [internal.py:wandb_internal():86] W&B internal server running at pid: 36244, started at: 2024-08-07 18:46:08.188622
2024-08-07 18:46:08,191 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: status
2024-08-07 18:46:08,191 INFO    WriterThread:36244 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/run-t5evc4zy.wandb
2024-08-07 18:46:08,192 DEBUG   SenderThread:36244 [sender.py:send():382] send: header
2024-08-07 18:46:08,225 DEBUG   SenderThread:36244 [sender.py:send():382] send: run
2024-08-07 18:46:08,374 INFO    SenderThread:36244 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files
2024-08-07 18:46:08,374 INFO    SenderThread:36244 [sender.py:_start_run_threads():1136] run started: t5evc4zy with start time 1723027568.18868
2024-08-07 18:46:08,379 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: check_version
2024-08-07 18:46:08,379 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: check_version
2024-08-07 18:46:08,475 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: run_start
2024-08-07 18:46:08,490 DEBUG   HandlerThread:36244 [system_info.py:__init__():32] System info init
2024-08-07 18:46:08,490 DEBUG   HandlerThread:36244 [system_info.py:__init__():47] System info init done
2024-08-07 18:46:08,490 INFO    HandlerThread:36244 [system_monitor.py:start():194] Starting system monitor
2024-08-07 18:46:08,490 INFO    SystemMonitor:36244 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-07 18:46:08,491 INFO    HandlerThread:36244 [system_monitor.py:probe():214] Collecting system info
2024-08-07 18:46:08,491 INFO    SystemMonitor:36244 [interfaces.py:start():190] Started cpu monitoring
2024-08-07 18:46:08,492 INFO    SystemMonitor:36244 [interfaces.py:start():190] Started disk monitoring
2024-08-07 18:46:08,494 INFO    SystemMonitor:36244 [interfaces.py:start():190] Started gpu monitoring
2024-08-07 18:46:08,495 INFO    SystemMonitor:36244 [interfaces.py:start():190] Started memory monitoring
2024-08-07 18:46:08,495 INFO    SystemMonitor:36244 [interfaces.py:start():190] Started network monitoring
2024-08-07 18:46:08,506 DEBUG   HandlerThread:36244 [system_info.py:probe():196] Probing system
2024-08-07 18:46:08,508 DEBUG   HandlerThread:36244 [system_info.py:_probe_git():181] Probing git
2024-08-07 18:46:08,511 DEBUG   HandlerThread:36244 [system_info.py:_probe_git():189] Probing git done
2024-08-07 18:46:08,511 DEBUG   HandlerThread:36244 [system_info.py:probe():244] Probing system done
2024-08-07 18:46:08,511 DEBUG   HandlerThread:36244 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-07T10:46:08.506783', 'startedAt': '2024-08-07T10:46:08.176085', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1095.6680000000001, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1417.734, 'min': 800.0, 'max': 5500.0}, {'current': 1651.884, 'min': 800.0, 'max': 5500.0}, {'current': 1410.015, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1489.355, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1446.696, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1636.377, 'min': 800.0, 'max': 5600.0}, {'current': 1499.891, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1480.453, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1515.544, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1529.52, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 474.6860122680664}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-07 18:46:08,511 INFO    HandlerThread:36244 [system_monitor.py:probe():224] Finished collecting system info
2024-08-07 18:46:08,511 INFO    HandlerThread:36244 [system_monitor.py:probe():227] Publishing system info
2024-08-07 18:46:08,511 DEBUG   HandlerThread:36244 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-07 18:46:08,511 DEBUG   HandlerThread:36244 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-07 18:46:08,511 DEBUG   HandlerThread:36244 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-07 18:46:09,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/requirements.txt
2024-08-07 18:46:09,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/conda-environment.yaml
2024-08-07 18:46:10,215 DEBUG   HandlerThread:36244 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-07 18:46:10,215 DEBUG   HandlerThread:36244 [system_info.py:_save_code():90] Saving code
2024-08-07 18:46:10,216 DEBUG   HandlerThread:36244 [system_info.py:_save_code():111] Saving code done
2024-08-07 18:46:10,216 DEBUG   HandlerThread:36244 [system_info.py:_save_patches():128] Saving git patches
2024-08-07 18:46:10,256 DEBUG   HandlerThread:36244 [system_info.py:_save_patches():170] Saving git patches done
2024-08-07 18:46:10,256 INFO    HandlerThread:36244 [system_monitor.py:probe():229] Finished publishing system info
2024-08-07 18:46:10,259 DEBUG   SenderThread:36244 [sender.py:send():382] send: files
2024-08-07 18:46:10,259 INFO    SenderThread:36244 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-07 18:46:10,260 INFO    SenderThread:36244 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-07 18:46:10,260 INFO    SenderThread:36244 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-07 18:46:10,268 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: stop_status
2024-08-07 18:46:10,268 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-07 18:46:10,269 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: stop_status
2024-08-07 18:46:10,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/conda-environment.yaml
2024-08-07 18:46:10,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/code/llama/gmm.py
2024-08-07 18:46:10,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/wandb-metadata.json
2024-08-07 18:46:10,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/diff.patch
2024-08-07 18:46:10,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/code
2024-08-07 18:46:10,374 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/code/llama
2024-08-07 18:46:10,513 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112
2024-08-07 18:46:10,513 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:10,513 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96C724514D0DE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: telemetry
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: config
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: metric
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: telemetry
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: metric
2024-08-07 18:46:10,522 WARNING SenderThread:36244 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: telemetry
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: telemetry
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: config
2024-08-07 18:46:10,522 DEBUG   SenderThread:36244 [sender.py:send():382] send: exit
2024-08-07 18:46:10,522 INFO    SenderThread:36244 [sender.py:send_exit():589] handling exit code: 1
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:send_exit():591] handling runtime: 2
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:send_exit():597] send defer
2024-08-07 18:46:10,523 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,523 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-07 18:46:10,523 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 1
2024-08-07 18:46:10,523 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,523 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-07 18:46:10,523 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-07 18:46:10,523 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 2
2024-08-07 18:46:10,523 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,523 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-07 18:46:10,523 INFO    HandlerThread:36244 [system_monitor.py:finish():203] Stopping system monitor
2024-08-07 18:46:10,523 DEBUG   SystemMonitor:36244 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-07 18:46:10,524 INFO    HandlerThread:36244 [interfaces.py:finish():202] Joined cpu monitor
2024-08-07 18:46:10,524 DEBUG   SystemMonitor:36244 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-07 18:46:10,524 INFO    HandlerThread:36244 [interfaces.py:finish():202] Joined disk monitor
2024-08-07 18:46:10,524 DEBUG   SystemMonitor:36244 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [interfaces.py:finish():202] Joined gpu monitor
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [interfaces.py:finish():202] Joined memory monitor
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [interfaces.py:finish():202] Joined network monitor
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 3
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send():382] send: stats
2024-08-07 18:46:10,546 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 4
2024-08-07 18:46:10,546 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 5
2024-08-07 18:46:10,546 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send():382] send: summary
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 6
2024-08-07 18:46:10,546 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,546 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-07 18:46:10,546 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,546 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-07 18:46:10,548 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: status_report
2024-08-07 18:46:10,660 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 7
2024-08-07 18:46:10,660 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:10,660 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-07 18:46:10,660 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:10,661 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-07 18:46:10,780 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c
2024-08-07 18:46:10,780 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290107', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:10,780 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96C724B979A5E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:11,375 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/config.yaml
2024-08-07 18:46:11,375 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/wandb-summary.json
2024-08-07 18:46:11,376 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/output.log
2024-08-07 18:46:11,510 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 18:46:11,565 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112
2024-08-07 18:46:11,565 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:11,565 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96C7285E5B0F1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:11,589 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882
2024-08-07 18:46:11,589 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5211', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:11,589 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96C72820D55AF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:12,537 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 8
2024-08-07 18:46:12,537 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: poll_exit
2024-08-07 18:46:12,537 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:12,537 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-07 18:46:12,538 DEBUG   SenderThread:36244 [sender.py:send_request():409] send_request: defer
2024-08-07 18:46:12,538 INFO    SenderThread:36244 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-07 18:46:12,538 INFO    SenderThread:36244 [job_builder.py:build():298] Attempting to build job artifact
2024-08-07 18:46:12,538 INFO    SenderThread:36244 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-07 18:46:12,556 INFO    SenderThread:36244 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-07 18:46:12,570 INFO    SenderThread:36244 [sender.py:transition_state():617] send defer: 9
2024-08-07 18:46:12,570 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:46:12,570 INFO    HandlerThread:36244 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-07 18:46:12,571 DEBUG   SenderThread:36244 [sender.py:send():382] send: artifact
2024-08-07 18:46:12,636 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c
2024-08-07 18:46:12,636 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290107', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:12,636 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96C72A262517D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:12,636 INFO    wandb-upload_2:36244 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:46:12,857 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882
2024-08-07 18:46:12,857 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5211', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:12,857 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96C72D2DB4AB5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:13,376 INFO    Thread-12 :36244 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_184608-t5evc4zy/files/output.log
2024-08-07 18:46:13,668 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226
2024-08-07 18:46:13,668 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:13,668 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96C730325A188</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:13,718 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112
2024-08-07 18:46:13,719 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:13,719 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96C7305B54FB5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:13,952 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea
2024-08-07 18:46:13,952 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:13,952 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96C7303374EDA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:14,934 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226
2024-08-07 18:46:14,934 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:14,934 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96C734A50305A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:15,023 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882
2024-08-07 18:46:15,023 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5211', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:15,023 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96C735417C3E5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:15,257 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7f4193af37e2b1c1c15f25d8b9a29da4b058baf1058f74b93c604c6d8497e53c
2024-08-07 18:46:15,257 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290107', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:15,257 ERROR   wandb-upload_2:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96C734D7D4D80</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:15,315 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea
2024-08-07 18:46:15,316 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:15,316 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96C7362FE3384</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:16,512 DEBUG   HandlerThread:36244 [handler.py:handle_request():146] handle_request: keepalive
2024-08-07 18:46:17,409 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226
2024-08-07 18:46:17,409 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:17,409 ERROR   wandb-upload_3:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96C73E1D3C98B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:17,410 INFO    wandb-upload_3:36244 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=87cc95282808cd3f1ce5e5dc54a856719adea7742e6db12a95c677b83c2e8226

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:46:18,339 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea
2024-08-07 18:46:18,339 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:18,339 ERROR   wandb-upload_4:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96C73FAF0A009</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:18,340 INFO    wandb-upload_4:36244 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/518/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104613Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=a0b30bb8c9e02752b47c38f8da2cbf37727359eb72106cdd7a99573181bac2ea

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:46:18,401 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8292383272fcd9d464bea9435a641aa7be06d4403f3b1c845e02b1910fff7112
2024-08-07 18:46:18,402 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:18,402 ERROR   wandb-upload_1:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96C741CCBE50F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:46:19,375 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T104610Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3912105c8e172962b54f105d8be0b8e3c2f949e62f1e8396b9273c165eefa882
2024-08-07 18:46:19,375 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5211', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:46:19,375 ERROR   wandb-upload_0:36244 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/t5evc4zy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/t5evc4zy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96C745758387B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
