2024-08-06 19:00:11,612 INFO    StreamThr :2118116 [internal.py:wandb_internal():86] W&B internal server running at pid: 2118116, started at: 2024-08-06 19:00:11.611840
2024-08-06 19:00:11,613 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: status
2024-08-06 19:00:11,613 INFO    WriterThread:2118116 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/run-j67zbn9o.wandb
2024-08-06 19:00:11,613 DEBUG   SenderThread:2118116 [sender.py:send():382] send: header
2024-08-06 19:00:11,614 DEBUG   SenderThread:2118116 [sender.py:send():382] send: run
2024-08-06 19:00:12,156 INFO    SenderThread:2118116 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files
2024-08-06 19:00:12,156 INFO    SenderThread:2118116 [sender.py:_start_run_threads():1136] run started: j67zbn9o with start time 1722942011.611805
2024-08-06 19:00:12,162 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 19:00:12,162 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: check_version
2024-08-06 19:00:12,269 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 19:00:12,279 DEBUG   HandlerThread:2118116 [system_info.py:__init__():32] System info init
2024-08-06 19:00:12,279 DEBUG   HandlerThread:2118116 [system_info.py:__init__():47] System info init done
2024-08-06 19:00:12,279 INFO    HandlerThread:2118116 [system_monitor.py:start():194] Starting system monitor
2024-08-06 19:00:12,279 INFO    SystemMonitor:2118116 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 19:00:12,279 INFO    SystemMonitor:2118116 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 19:00:12,279 INFO    SystemMonitor:2118116 [interfaces.py:start():190] Started disk monitoring
2024-08-06 19:00:12,279 INFO    HandlerThread:2118116 [system_monitor.py:probe():214] Collecting system info
2024-08-06 19:00:12,280 INFO    SystemMonitor:2118116 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 19:00:12,280 INFO    SystemMonitor:2118116 [interfaces.py:start():190] Started memory monitoring
2024-08-06 19:00:12,281 INFO    SystemMonitor:2118116 [interfaces.py:start():190] Started network monitoring
2024-08-06 19:00:12,286 DEBUG   HandlerThread:2118116 [system_info.py:probe():196] Probing system
2024-08-06 19:00:12,288 DEBUG   HandlerThread:2118116 [system_info.py:_probe_git():181] Probing git
2024-08-06 19:00:12,290 DEBUG   HandlerThread:2118116 [system_info.py:_probe_git():189] Probing git done
2024-08-06 19:00:12,290 DEBUG   HandlerThread:2118116 [system_info.py:probe():244] Probing system done
2024-08-06 19:00:12,290 DEBUG   HandlerThread:2118116 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T11:00:12.286959', 'startedAt': '2024-08-06T11:00:11.607245', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2b', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1382.2043571428571, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 4473.999, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4538.857, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 5370.965, 'min': 800.0, 'max': 5600.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 1165.319, 'min': 800.0, 'max': 5500.0}, {'current': 5499.58, 'min': 800.0, 'max': 5500.0}, {'current': 5408.282, 'min': 800.0, 'max': 5500.0}, {'current': 1313.271, 'min': 800.0, 'max': 5500.0}, {'current': 1099.546, 'min': 800.0, 'max': 4300.0}, {'current': 1295.938, 'min': 800.0, 'max': 4300.0}, {'current': 1100.522, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1099.236, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.36641693115234}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 19:00:12,290 INFO    HandlerThread:2118116 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 19:00:12,290 INFO    HandlerThread:2118116 [system_monitor.py:probe():227] Publishing system info
2024-08-06 19:00:12,290 DEBUG   HandlerThread:2118116 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 19:00:12,290 DEBUG   HandlerThread:2118116 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 19:00:12,290 DEBUG   HandlerThread:2118116 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 19:00:13,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/conda-environment.yaml
2024-08-06 19:00:13,157 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/requirements.txt
2024-08-06 19:00:13,981 DEBUG   HandlerThread:2118116 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 19:00:13,981 DEBUG   HandlerThread:2118116 [system_info.py:_save_code():90] Saving code
2024-08-06 19:00:13,983 DEBUG   HandlerThread:2118116 [system_info.py:_save_code():111] Saving code done
2024-08-06 19:00:13,983 DEBUG   HandlerThread:2118116 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 19:00:13,985 ERROR   HandlerThread:2118116 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 19:00:13,985 DEBUG   HandlerThread:2118116 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 19:00:13,986 INFO    HandlerThread:2118116 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 19:00:13,986 DEBUG   SenderThread:2118116 [sender.py:send():382] send: files
2024-08-06 19:00:13,987 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 19:00:13,987 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 19:00:13,989 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:00:13,989 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:00:13,989 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:00:14,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/conda-environment.yaml
2024-08-06 19:00:14,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-metadata.json
2024-08-06 19:00:14,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/code/llama/gmm.py
2024-08-06 19:00:14,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/code
2024-08-06 19:00:14,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/code/llama
2024-08-06 19:00:14,233 DEBUG   SenderThread:2118116 [sender.py:send():382] send: telemetry
2024-08-06 19:00:14,233 DEBUG   SenderThread:2118116 [sender.py:send():382] send: config
2024-08-06 19:00:14,234 DEBUG   SenderThread:2118116 [sender.py:send():382] send: metric
2024-08-06 19:00:14,234 DEBUG   SenderThread:2118116 [sender.py:send():382] send: telemetry
2024-08-06 19:00:14,234 DEBUG   SenderThread:2118116 [sender.py:send():382] send: metric
2024-08-06 19:00:14,234 WARNING SenderThread:2118116 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 19:00:14,234 DEBUG   SenderThread:2118116 [sender.py:send():382] send: telemetry
2024-08-06 19:00:14,234 DEBUG   SenderThread:2118116 [sender.py:send():382] send: telemetry
2024-08-06 19:00:14,234 DEBUG   SenderThread:2118116 [sender.py:send():382] send: config
2024-08-06 19:00:14,257 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5
2024-08-06 19:00:14,257 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:14,257 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91EA2261A58A5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:14,417 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a
2024-08-06 19:00:14,417 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:14,417 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91EA22BB84392</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:15,156 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:15,512 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a
2024-08-06 19:00:15,512 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:15,512 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91EA270426B60</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:15,512 INFO    wandb-upload_1:2118116 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:00:15,820 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5
2024-08-06 19:00:15,820 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:15,820 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91EA26F8D8720</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:15,820 INFO    wandb-upload_0:2118116 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:00:16,833 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:00:16,833 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:16,834 DEBUG   SenderThread:2118116 [sender.py:send():382] send: metric
2024-08-06 19:00:16,834 DEBUG   SenderThread:2118116 [sender.py:send():382] send: metric
2024-08-06 19:00:16,834 DEBUG   SenderThread:2118116 [sender.py:send():382] send: metric
2024-08-06 19:00:16,834 DEBUG   SenderThread:2118116 [sender.py:send():382] send: metric
2024-08-06 19:00:16,834 DEBUG   SenderThread:2118116 [sender.py:send():382] send: history
2024-08-06 19:00:16,834 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:00:16,834 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:00:17,157 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:17,157 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-summary.json
2024-08-06 19:00:18,176 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a
2024-08-06 19:00:18,176 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:18,176 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91EA309867279</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:18,206 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5
2024-08-06 19:00:18,206 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:18,206 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91EA311422911</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:19,157 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:19,281 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:19,282 DEBUG   SenderThread:2118116 [sender.py:send():382] send: history
2024-08-06 19:00:19,282 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:00:19,282 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:00:20,157 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-summary.json
2024-08-06 19:00:21,158 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:21,510 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:21,510 DEBUG   SenderThread:2118116 [sender.py:send():382] send: history
2024-08-06 19:00:21,510 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:00:21,511 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:00:22,158 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-summary.json
2024-08-06 19:00:22,511 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:00:22,690 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5
2024-08-06 19:00:22,691 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:22,691 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91EA41C99D262</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:22,709 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a
2024-08-06 19:00:22,709 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:22,709 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91EA41CE18508</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:23,158 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:23,945 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:23,945 DEBUG   SenderThread:2118116 [sender.py:send():382] send: history
2024-08-06 19:00:23,945 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:00:23,945 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:00:24,158 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-summary.json
2024-08-06 19:00:25,158 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:26,323 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:26,323 DEBUG   SenderThread:2118116 [sender.py:send():382] send: history
2024-08-06 19:00:26,324 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:00:26,324 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:00:27,159 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:27,159 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-summary.json
2024-08-06 19:00:28,324 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:00:28,666 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:28,667 DEBUG   SenderThread:2118116 [sender.py:send():382] send: history
2024-08-06 19:00:28,667 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:00:28,667 INFO    SenderThread:2118116 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:00:28,989 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:00:28,989 DEBUG   SenderThread:2118116 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:00:28,990 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:00:29,159 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:29,159 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/wandb-summary.json
2024-08-06 19:00:30,858 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2498e1e35df0022b15201e3c30b8830ae0882fc6856f08ed3066bf488e6ad4e5
2024-08-06 19:00:30,858 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:30,858 ERROR   wandb-upload_0:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91EA6038784E4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:31,038 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:31,160 INFO    Thread-12 :2118116 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190011-j67zbn9o/files/output.log
2024-08-06 19:00:32,505 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110014Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12dfb4b2435c52670d733c65f3e273604fd1c7f8a77e7c269fb5796651176e2a
2024-08-06 19:00:32,505 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:00:32,505 ERROR   wandb-upload_1:2118116 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/j67zbn9o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/j67zbn9o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91EA65ECF8D89</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:00:33,359 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:33,989 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 19:00:35,674 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:37,950 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:38,990 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 19:00:40,396 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:42,623 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:43,989 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:00:45,102 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:47,554 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:00:48,991 DEBUG   HandlerThread:2118116 [handler.py:handle_request():146] handle_request: keepalive
