2024-08-08 18:04:53,689 INFO    StreamThr :311020 [internal.py:wandb_internal():86] W&B internal server running at pid: 311020, started at: 2024-08-08 18:04:53.689496
2024-08-08 18:04:53,690 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: status
2024-08-08 18:04:53,692 INFO    WriterThread:311020 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/run-cyhl7xfe.wandb
2024-08-08 18:04:53,692 DEBUG   SenderThread:311020 [sender.py:send():382] send: header
2024-08-08 18:04:53,726 DEBUG   SenderThread:311020 [sender.py:send():382] send: run
2024-08-08 18:04:53,962 INFO    SenderThread:311020 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files
2024-08-08 18:04:53,962 INFO    SenderThread:311020 [sender.py:_start_run_threads():1136] run started: cyhl7xfe with start time 1723111493.689476
2024-08-08 18:04:53,968 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 18:04:53,968 DEBUG   SenderThread:311020 [sender.py:send_request():409] send_request: check_version
2024-08-08 18:04:54,098 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 18:04:54,110 DEBUG   HandlerThread:311020 [system_info.py:__init__():32] System info init
2024-08-08 18:04:54,110 DEBUG   HandlerThread:311020 [system_info.py:__init__():47] System info init done
2024-08-08 18:04:54,110 INFO    HandlerThread:311020 [system_monitor.py:start():194] Starting system monitor
2024-08-08 18:04:54,110 INFO    SystemMonitor:311020 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 18:04:54,111 INFO    HandlerThread:311020 [system_monitor.py:probe():214] Collecting system info
2024-08-08 18:04:54,112 INFO    SystemMonitor:311020 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 18:04:54,115 INFO    SystemMonitor:311020 [interfaces.py:start():190] Started disk monitoring
2024-08-08 18:04:54,116 INFO    SystemMonitor:311020 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 18:04:54,118 INFO    SystemMonitor:311020 [interfaces.py:start():190] Started memory monitoring
2024-08-08 18:04:54,118 INFO    SystemMonitor:311020 [interfaces.py:start():190] Started network monitoring
2024-08-08 18:04:54,132 DEBUG   HandlerThread:311020 [system_info.py:probe():196] Probing system
2024-08-08 18:04:54,134 DEBUG   HandlerThread:311020 [system_info.py:_probe_git():181] Probing git
2024-08-08 18:04:54,138 DEBUG   HandlerThread:311020 [system_info.py:_probe_git():189] Probing git done
2024-08-08 18:04:54,138 DEBUG   HandlerThread:311020 [system_info.py:probe():244] Probing system done
2024-08-08 18:04:54,138 DEBUG   HandlerThread:311020 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T10:04:54.133024', 'startedAt': '2024-08-08T10:04:53.685708', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 938.80425, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1085.945, 'min': 800.0, 'max': 5500.0}, {'current': 1103.248, 'min': 800.0, 'max': 5500.0}, {'current': 1109.897, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1155.711, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1157.061, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1111.842, 'min': 800.0, 'max': 5600.0}, {'current': 1100.517, 'min': 800.0, 'max': 5600.0}, {'current': 1111.983, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1107.729, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1107.505, 'min': 800.0, 'max': 5500.0}, {'current': 1100.0, 'min': 800.0, 'max': 5500.0}, {'current': 1183.801, 'min': 800.0, 'max': 4300.0}, {'current': 1116.588, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0329818725586}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 18:04:54,138 INFO    HandlerThread:311020 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 18:04:54,138 INFO    HandlerThread:311020 [system_monitor.py:probe():227] Publishing system info
2024-08-08 18:04:54,138 DEBUG   HandlerThread:311020 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 18:04:54,138 DEBUG   HandlerThread:311020 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 18:04:54,138 DEBUG   HandlerThread:311020 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 18:04:54,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/conda-environment.yaml
2024-08-08 18:04:54,963 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/requirements.txt
2024-08-08 18:04:55,805 DEBUG   HandlerThread:311020 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 18:04:55,805 DEBUG   HandlerThread:311020 [system_info.py:_save_code():90] Saving code
2024-08-08 18:04:55,806 DEBUG   HandlerThread:311020 [system_info.py:_save_code():111] Saving code done
2024-08-08 18:04:55,806 DEBUG   HandlerThread:311020 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 18:04:55,846 DEBUG   HandlerThread:311020 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 18:04:55,846 INFO    HandlerThread:311020 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 18:04:55,849 DEBUG   SenderThread:311020 [sender.py:send():382] send: files
2024-08-08 18:04:55,849 INFO    SenderThread:311020 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 18:04:55,850 INFO    SenderThread:311020 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 18:04:55,851 INFO    SenderThread:311020 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 18:04:55,858 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 18:04:55,860 DEBUG   SenderThread:311020 [sender.py:send_request():409] send_request: stop_status
2024-08-08 18:04:55,865 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 18:04:55,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/conda-environment.yaml
2024-08-08 18:04:55,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/code/llama/gmm.py
2024-08-08 18:04:55,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/diff.patch
2024-08-08 18:04:55,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/wandb-metadata.json
2024-08-08 18:04:55,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/code
2024-08-08 18:04:55,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/code/llama
2024-08-08 18:04:56,087 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8
2024-08-08 18:04:56,087 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5246', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:56,087 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C6B73637C4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: telemetry
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: config
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: metric
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: telemetry
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: metric
2024-08-08 18:04:56,100 WARNING SenderThread:311020 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: telemetry
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: telemetry
2024-08-08 18:04:56,100 DEBUG   SenderThread:311020 [sender.py:send():382] send: config
2024-08-08 18:04:56,203 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776
2024-08-08 18:04:56,204 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:56,204 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8C6B9E0900E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:56,654 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100456Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=13af0bea0fea6ec313f0b65f6ef98fd57496713405c6f57147abd961270c8a1d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100456Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=13af0bea0fea6ec313f0b65f6ef98fd57496713405c6f57147abd961270c8a1d
2024-08-08 18:04:56,654 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291937', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:56,654 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8C6BF181514</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:56,962 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/output.log
2024-08-08 18:04:57,337 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776
2024-08-08 18:04:57,337 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:57,337 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8C701A1D410</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:57,337 INFO    wandb-upload_1:311020 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 18:04:57,728 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8
2024-08-08 18:04:57,729 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5246', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:57,729 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C7043DF18C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:57,729 INFO    wandb-upload_0:311020 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 18:04:58,205 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100456Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=13af0bea0fea6ec313f0b65f6ef98fd57496713405c6f57147abd961270c8a1d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100456Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=13af0bea0fea6ec313f0b65f6ef98fd57496713405c6f57147abd961270c8a1d
2024-08-08 18:04:58,205 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291937', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:58,205 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8C7215CB2D2</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:58,757 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 18:04:58,757 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 18:04:58,758 DEBUG   SenderThread:311020 [sender.py:send():382] send: metric
2024-08-08 18:04:58,758 DEBUG   SenderThread:311020 [sender.py:send():382] send: metric
2024-08-08 18:04:58,758 DEBUG   SenderThread:311020 [sender.py:send():382] send: metric
2024-08-08 18:04:58,758 DEBUG   SenderThread:311020 [sender.py:send():382] send: metric
2024-08-08 18:04:58,758 DEBUG   SenderThread:311020 [sender.py:send():382] send: history
2024-08-08 18:04:58,758 DEBUG   SenderThread:311020 [sender.py:send_request():409] send_request: summary_record
2024-08-08 18:04:58,758 INFO    SenderThread:311020 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 18:04:58,963 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/output.log
2024-08-08 18:04:58,963 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/wandb-summary.json
2024-08-08 18:04:59,608 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1d99625e8b327a6d84926e757906774ac2ca74fa29136aa18d88e6e68c891776
2024-08-08 18:04:59,608 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:59,608 ERROR   wandb-upload_1:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8C788D89E44</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:05:00,052 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100455Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b2eb8205f828885cb8387f5551f218f1a77866c06d657a5a2479bd42701fffc8
2024-08-08 18:05:00,052 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5246', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:05:00,052 ERROR   wandb-upload_0:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C7A35F8A21</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:05:00,738 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100456Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=13af0bea0fea6ec313f0b65f6ef98fd57496713405c6f57147abd961270c8a1d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/cyhl7xfe/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100456Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=13af0bea0fea6ec313f0b65f6ef98fd57496713405c6f57147abd961270c8a1d
2024-08-08 18:05:00,738 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291937', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:05:00,738 ERROR   wandb-upload_2:311020 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/cyhl7xfe/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/cyhl7xfe/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8C7C6A7DF65</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:05:00,963 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/output.log
2024-08-08 18:05:01,280 DEBUG   HandlerThread:311020 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 18:05:01,280 DEBUG   SenderThread:311020 [sender.py:send():382] send: history
2024-08-08 18:05:01,280 DEBUG   SenderThread:311020 [sender.py:send_request():409] send_request: summary_record
2024-08-08 18:05:01,280 INFO    SenderThread:311020 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 18:05:01,964 INFO    Thread-12 :311020 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180453-cyhl7xfe/files/wandb-summary.json
