2024-08-08 18:04:35,774 INFO    StreamThr :310594 [internal.py:wandb_internal():86] W&B internal server running at pid: 310594, started at: 2024-08-08 18:04:35.774409
2024-08-08 18:04:35,776 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: status
2024-08-08 18:04:35,777 INFO    WriterThread:310594 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/run-hud92jbx.wandb
2024-08-08 18:04:35,778 DEBUG   SenderThread:310594 [sender.py:send():382] send: header
2024-08-08 18:04:35,802 DEBUG   SenderThread:310594 [sender.py:send():382] send: run
2024-08-08 18:04:35,963 INFO    SenderThread:310594 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files
2024-08-08 18:04:35,964 INFO    SenderThread:310594 [sender.py:_start_run_threads():1136] run started: hud92jbx with start time 1723111475.774278
2024-08-08 18:04:35,976 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 18:04:35,976 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: check_version
2024-08-08 18:04:36,082 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 18:04:36,090 DEBUG   HandlerThread:310594 [system_info.py:__init__():32] System info init
2024-08-08 18:04:36,090 DEBUG   HandlerThread:310594 [system_info.py:__init__():47] System info init done
2024-08-08 18:04:36,090 INFO    HandlerThread:310594 [system_monitor.py:start():194] Starting system monitor
2024-08-08 18:04:36,090 INFO    SystemMonitor:310594 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 18:04:36,090 INFO    HandlerThread:310594 [system_monitor.py:probe():214] Collecting system info
2024-08-08 18:04:36,090 INFO    SystemMonitor:310594 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 18:04:36,091 INFO    SystemMonitor:310594 [interfaces.py:start():190] Started disk monitoring
2024-08-08 18:04:36,091 INFO    SystemMonitor:310594 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 18:04:36,092 INFO    SystemMonitor:310594 [interfaces.py:start():190] Started memory monitoring
2024-08-08 18:04:36,092 INFO    SystemMonitor:310594 [interfaces.py:start():190] Started network monitoring
2024-08-08 18:04:36,099 DEBUG   HandlerThread:310594 [system_info.py:probe():196] Probing system
2024-08-08 18:04:36,101 DEBUG   HandlerThread:310594 [system_info.py:_probe_git():181] Probing git
2024-08-08 18:04:36,107 DEBUG   HandlerThread:310594 [system_info.py:_probe_git():189] Probing git done
2024-08-08 18:04:36,107 DEBUG   HandlerThread:310594 [system_info.py:probe():244] Probing system done
2024-08-08 18:04:36,107 DEBUG   HandlerThread:310594 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T10:04:36.099691', 'startedAt': '2024-08-08T10:04:35.769487', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1653.5617857142859, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 2909.076, 'min': 800.0, 'max': 5500.0}, {'current': 5053.421, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2537.952, 'min': 800.0, 'max': 5500.0}, {'current': 2095.831, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5060.048, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4026.515, 'min': 800.0, 'max': 5600.0}, {'current': 3728.019, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 5391.595, 'min': 800.0, 'max': 5600.0}, {'current': 5039.357, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2550.742, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2305.881, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0318298339844}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 18:04:36,107 INFO    HandlerThread:310594 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 18:04:36,108 INFO    HandlerThread:310594 [system_monitor.py:probe():227] Publishing system info
2024-08-08 18:04:36,108 DEBUG   HandlerThread:310594 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 18:04:36,108 DEBUG   HandlerThread:310594 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 18:04:36,108 DEBUG   HandlerThread:310594 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 18:04:36,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/requirements.txt
2024-08-08 18:04:36,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/conda-environment.yaml
2024-08-08 18:04:37,767 DEBUG   HandlerThread:310594 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 18:04:37,767 DEBUG   HandlerThread:310594 [system_info.py:_save_code():90] Saving code
2024-08-08 18:04:37,768 DEBUG   HandlerThread:310594 [system_info.py:_save_code():111] Saving code done
2024-08-08 18:04:37,768 DEBUG   HandlerThread:310594 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 18:04:37,807 DEBUG   HandlerThread:310594 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 18:04:37,808 INFO    HandlerThread:310594 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 18:04:37,810 DEBUG   SenderThread:310594 [sender.py:send():382] send: files
2024-08-08 18:04:37,810 INFO    SenderThread:310594 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 18:04:37,811 INFO    SenderThread:310594 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 18:04:37,811 INFO    SenderThread:310594 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 18:04:37,818 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 18:04:37,819 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: stop_status
2024-08-08 18:04:37,826 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 18:04:37,963 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/conda-environment.yaml
2024-08-08 18:04:37,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/wandb-metadata.json
2024-08-08 18:04:37,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/code/llama/gmm.py
2024-08-08 18:04:37,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/diff.patch
2024-08-08 18:04:37,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/code
2024-08-08 18:04:37,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/code/llama
2024-08-08 18:04:37,986 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9
2024-08-08 18:04:37,986 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5251', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:37,986 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C28066E6FC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:38,060 DEBUG   SenderThread:310594 [sender.py:send():382] send: telemetry
2024-08-08 18:04:38,061 DEBUG   SenderThread:310594 [sender.py:send():382] send: config
2024-08-08 18:04:38,062 DEBUG   SenderThread:310594 [sender.py:send():382] send: metric
2024-08-08 18:04:38,062 DEBUG   SenderThread:310594 [sender.py:send():382] send: telemetry
2024-08-08 18:04:38,062 DEBUG   SenderThread:310594 [sender.py:send():382] send: metric
2024-08-08 18:04:38,062 WARNING SenderThread:310594 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 18:04:38,062 DEBUG   SenderThread:310594 [sender.py:send():382] send: telemetry
2024-08-08 18:04:38,062 DEBUG   SenderThread:310594 [sender.py:send():382] send: telemetry
2024-08-08 18:04:38,062 DEBUG   SenderThread:310594 [sender.py:send():382] send: config
2024-08-08 18:04:38,065 DEBUG   SenderThread:310594 [sender.py:send():382] send: exit
2024-08-08 18:04:38,065 INFO    SenderThread:310594 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 18:04:38,065 INFO    SenderThread:310594 [sender.py:send_exit():591] handling runtime: 1
2024-08-08 18:04:38,068 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c
2024-08-08 18:04:38,068 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:38,069 INFO    SenderThread:310594 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 18:04:38,069 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8C284C7E4B8</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:38,069 INFO    SenderThread:310594 [sender.py:send_exit():597] send defer
2024-08-08 18:04:38,070 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,070 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 18:04:38,070 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,071 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 18:04:38,071 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 1
2024-08-08 18:04:38,071 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,071 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 18:04:38,071 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,071 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 18:04:38,071 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 2
2024-08-08 18:04:38,072 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,072 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 18:04:38,072 INFO    HandlerThread:310594 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 18:04:38,072 DEBUG   SystemMonitor:310594 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 18:04:38,073 DEBUG   SystemMonitor:310594 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 18:04:38,073 DEBUG   SystemMonitor:310594 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 18:04:38,074 INFO    HandlerThread:310594 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 18:04:38,074 INFO    HandlerThread:310594 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 18:04:38,109 INFO    HandlerThread:310594 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 18:04:38,109 INFO    HandlerThread:310594 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 18:04:38,109 INFO    HandlerThread:310594 [interfaces.py:finish():202] Joined network monitor
2024-08-08 18:04:38,109 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,109 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 18:04:38,109 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 3
2024-08-08 18:04:38,109 DEBUG   SenderThread:310594 [sender.py:send():382] send: stats
2024-08-08 18:04:38,109 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,110 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 18:04:38,110 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 4
2024-08-08 18:04:38,110 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,110 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 18:04:38,110 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 5
2024-08-08 18:04:38,110 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,110 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 18:04:38,110 DEBUG   SenderThread:310594 [sender.py:send():382] send: summary
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 18:04:38,110 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 6
2024-08-08 18:04:38,110 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,110 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 18:04:38,110 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,110 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 18:04:38,112 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 18:04:38,210 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 7
2024-08-08 18:04:38,210 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:38,210 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 18:04:38,210 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:38,210 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 18:04:38,563 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100438Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=faebd7dfdacf03817a4e93c9e3bd56a52376a5f657568b6b7c41b72f13418313: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100438Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=faebd7dfdacf03817a4e93c9e3bd56a52376a5f657568b6b7c41b72f13418313
2024-08-08 18:04:38,563 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291933', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:38,563 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8C28B430F5C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:38,964 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/config.yaml
2024-08-08 18:04:38,965 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/wandb-summary.json
2024-08-08 18:04:38,965 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/output.log
2024-08-08 18:04:39,009 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 18:04:39,181 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9
2024-08-08 18:04:39,181 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5251', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:39,181 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C2C756EC04</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:39,426 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c
2024-08-08 18:04:39,426 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:39,426 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8C2D06CB05C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:39,426 INFO    wandb-upload_1:310594 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 18:04:40,011 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100438Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=faebd7dfdacf03817a4e93c9e3bd56a52376a5f657568b6b7c41b72f13418313: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100438Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=faebd7dfdacf03817a4e93c9e3bd56a52376a5f657568b6b7c41b72f13418313
2024-08-08 18:04:40,011 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291933', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:40,012 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8C2EDE8B48D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:40,077 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 8
2024-08-08 18:04:40,077 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 18:04:40,077 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:40,078 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 18:04:40,078 DEBUG   SenderThread:310594 [sender.py:send_request():409] send_request: defer
2024-08-08 18:04:40,078 INFO    SenderThread:310594 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 18:04:40,078 INFO    SenderThread:310594 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 18:04:40,079 INFO    SenderThread:310594 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 18:04:40,098 INFO    SenderThread:310594 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 18:04:40,108 INFO    SenderThread:310594 [sender.py:transition_state():617] send defer: 9
2024-08-08 18:04:40,109 DEBUG   SenderThread:310594 [sender.py:send():382] send: artifact
2024-08-08 18:04:40,110 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: defer
2024-08-08 18:04:40,110 INFO    HandlerThread:310594 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 18:04:40,727 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3
2024-08-08 18:04:40,727 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:40,727 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B8C32394329E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:40,801 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c
2024-08-08 18:04:40,802 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'j2QuBeGKIA67VLXs8rRsjw==', 'Content-MD5': 'j2QuBeGKIA67VLXs8rRsjw==', 'Content-Type': 'application/json', 'Content-Length': '25171', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:40,802 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f</Resource><Region>wandb-local</Region><RequestId>17E9B8C3235B2F96</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:40,965 INFO    Thread-12 :310594 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180435-hud92jbx/files/output.log
2024-08-08 18:04:41,308 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9
2024-08-08 18:04:41,308 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5251', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:41,308 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C3461C1040</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:41,773 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cdeb3f43f57e46003fbf8fdd1b269d48a3b767e1768d8757a1872e87dbad870c
2024-08-08 18:04:41,773 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:41,773 ERROR   wandb-upload_1:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8C361CFC3DD</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:41,891 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3
2024-08-08 18:04:41,891 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:41,891 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B8C368E4D332</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:42,092 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c
2024-08-08 18:04:42,092 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'j2QuBeGKIA67VLXs8rRsjw==', 'Content-MD5': 'j2QuBeGKIA67VLXs8rRsjw==', 'Content-Type': 'application/json', 'Content-Length': '25171', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:42,092 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f</Resource><Region>wandb-local</Region><RequestId>17E9B8C36F3026E3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:42,658 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100438Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=faebd7dfdacf03817a4e93c9e3bd56a52376a5f657568b6b7c41b72f13418313: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100438Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=faebd7dfdacf03817a4e93c9e3bd56a52376a5f657568b6b7c41b72f13418313
2024-08-08 18:04:42,658 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291933', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:42,658 ERROR   wandb-upload_2:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8C39010920C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:44,011 DEBUG   HandlerThread:310594 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 18:04:44,259 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c
2024-08-08 18:04:44,259 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'j2QuBeGKIA67VLXs8rRsjw==', 'Content-MD5': 'j2QuBeGKIA67VLXs8rRsjw==', 'Content-Type': 'application/json', 'Content-Length': '25171', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:44,259 ERROR   wandb-upload_4:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f</Resource><Region>wandb-local</Region><RequestId>17E9B8C3F44A1840</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:44,259 INFO    wandb-upload_4:310594 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/8f642e05e18a200ebb54b5ecf2b46c8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=cdcab53f2c198dd219d4db6d3632eee75db81e4b4dc6212adbb4b903f249866c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 18:04:44,298 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3
2024-08-08 18:04:44,298 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:44,298 ERROR   wandb-upload_3:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9B8C3F8279136</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:04:44,298 INFO    wandb-upload_3:310594 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/528/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100440Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=7edb95734bb17db8836056ac4d2c15d72aeefa700e7873120a4151b32b45e9a3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 18:04:45,598 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100437Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f490f2639a7771bec6d58c584e0eb14ed7c8520a6a94a9a1080904cc2c5c0e9
2024-08-08 18:04:45,598 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5251', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:04:45,598 ERROR   wandb-upload_0:310594 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hud92jbx/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hud92jbx/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8C445CCB8A6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
