2024-08-06 15:47:00,473 INFO    StreamThr :2039649 [internal.py:wandb_internal():86] W&B internal server running at pid: 2039649, started at: 2024-08-06 15:47:00.473348
2024-08-06 15:47:00,474 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: status
2024-08-06 15:47:00,475 INFO    WriterThread:2039649 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/run-zitoe4ey.wandb
2024-08-06 15:47:00,475 DEBUG   SenderThread:2039649 [sender.py:send():382] send: header
2024-08-06 15:47:00,475 DEBUG   SenderThread:2039649 [sender.py:send():382] send: run
2024-08-06 15:47:00,713 INFO    SenderThread:2039649 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files
2024-08-06 15:47:00,713 INFO    SenderThread:2039649 [sender.py:_start_run_threads():1136] run started: zitoe4ey with start time 1722930420.473196
2024-08-06 15:47:00,719 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 15:47:00,719 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: check_version
2024-08-06 15:47:00,824 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 15:47:00,828 DEBUG   HandlerThread:2039649 [system_info.py:__init__():32] System info init
2024-08-06 15:47:00,828 DEBUG   HandlerThread:2039649 [system_info.py:__init__():47] System info init done
2024-08-06 15:47:00,828 INFO    HandlerThread:2039649 [system_monitor.py:start():194] Starting system monitor
2024-08-06 15:47:00,828 INFO    SystemMonitor:2039649 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 15:47:00,829 INFO    HandlerThread:2039649 [system_monitor.py:probe():214] Collecting system info
2024-08-06 15:47:00,829 INFO    SystemMonitor:2039649 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 15:47:00,829 INFO    SystemMonitor:2039649 [interfaces.py:start():190] Started disk monitoring
2024-08-06 15:47:00,830 INFO    SystemMonitor:2039649 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 15:47:00,830 INFO    SystemMonitor:2039649 [interfaces.py:start():190] Started memory monitoring
2024-08-06 15:47:00,830 INFO    SystemMonitor:2039649 [interfaces.py:start():190] Started network monitoring
2024-08-06 15:47:00,836 DEBUG   HandlerThread:2039649 [system_info.py:probe():196] Probing system
2024-08-06 15:47:00,838 DEBUG   HandlerThread:2039649 [system_info.py:_probe_git():181] Probing git
2024-08-06 15:47:00,840 DEBUG   HandlerThread:2039649 [system_info.py:_probe_git():189] Probing git done
2024-08-06 15:47:00,840 DEBUG   HandlerThread:2039649 [system_info.py:probe():244] Probing system done
2024-08-06 15:47:00,840 DEBUG   HandlerThread:2039649 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T07:47:00.836602', 'startedAt': '2024-08-06T07:47:00.468244', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--use_lora', 'True', '--init_lora_weights', 'pissa_niter_4', '--target_modules', 'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj', '--lora_rank', '32', '--lora_alpha', '32', '--lora_dropout', '0', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2121.779107142857, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 4143.18, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5483.659, 'min': 800.0, 'max': 5500.0}, {'current': 3565.457, 'min': 800.0, 'max': 5500.0}, {'current': 3146.267, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4134.862, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3774.715, 'min': 800.0, 'max': 5600.0}, {'current': 1123.484, 'min': 800.0, 'max': 5600.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4001.997, 'min': 800.0, 'max': 5500.0}, {'current': 3497.319, 'min': 800.0, 'max': 5500.0}, {'current': 1083.886, 'min': 800.0, 'max': 5500.0}, {'current': 1106.118, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1796.11, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 439.21777725219727}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 15:47:00,840 INFO    HandlerThread:2039649 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 15:47:00,840 INFO    HandlerThread:2039649 [system_monitor.py:probe():227] Publishing system info
2024-08-06 15:47:00,840 DEBUG   HandlerThread:2039649 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 15:47:00,841 DEBUG   HandlerThread:2039649 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 15:47:00,841 DEBUG   HandlerThread:2039649 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 15:47:01,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/conda-environment.yaml
2024-08-06 15:47:01,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/requirements.txt
2024-08-06 15:47:02,527 DEBUG   HandlerThread:2039649 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 15:47:02,527 DEBUG   HandlerThread:2039649 [system_info.py:_save_code():90] Saving code
2024-08-06 15:47:02,528 DEBUG   HandlerThread:2039649 [system_info.py:_save_code():111] Saving code done
2024-08-06 15:47:02,528 DEBUG   HandlerThread:2039649 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 15:47:02,531 ERROR   HandlerThread:2039649 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 15:47:02,531 DEBUG   HandlerThread:2039649 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 15:47:02,531 INFO    HandlerThread:2039649 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 15:47:02,532 DEBUG   SenderThread:2039649 [sender.py:send():382] send: files
2024-08-06 15:47:02,532 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 15:47:02,532 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 15:47:02,534 DEBUG   SenderThread:2039649 [sender.py:send():382] send: telemetry
2024-08-06 15:47:02,536 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 15:47:02,536 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 15:47:02,537 DEBUG   SenderThread:2039649 [sender.py:send():382] send: config
2024-08-06 15:47:02,537 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: stop_status
2024-08-06 15:47:02,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/conda-environment.yaml
2024-08-06 15:47:02,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/code/llama/gmm.py
2024-08-06 15:47:02,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/wandb-metadata.json
2024-08-06 15:47:02,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/code
2024-08-06 15:47:02,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/code/llama
2024-08-06 15:47:02,762 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad
2024-08-06 15:47:02,762 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5489', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:02,762 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914174B20AD49</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:02,774 DEBUG   SenderThread:2039649 [sender.py:send():382] send: metric
2024-08-06 15:47:02,774 DEBUG   SenderThread:2039649 [sender.py:send():382] send: telemetry
2024-08-06 15:47:02,774 DEBUG   SenderThread:2039649 [sender.py:send():382] send: metric
2024-08-06 15:47:02,774 WARNING SenderThread:2039649 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 15:47:02,774 DEBUG   SenderThread:2039649 [sender.py:send():382] send: telemetry
2024-08-06 15:47:02,774 DEBUG   SenderThread:2039649 [sender.py:send():382] send: telemetry
2024-08-06 15:47:02,774 DEBUG   SenderThread:2039649 [sender.py:send():382] send: config
2024-08-06 15:47:02,949 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc
2024-08-06 15:47:02,949 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '13917', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:02,949 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9141752C3E165</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:03,713 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:03,898 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad
2024-08-06 15:47:03,898 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5489', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:03,898 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914178EB2F103</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:04,234 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc
2024-08-06 15:47:04,234 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '13917', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:04,234 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E914179EC31346</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:04,234 INFO    wandb-upload_1:2039649 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 15:47:05,714 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:05,775 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 15:47:06,001 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 15:47:06,002 DEBUG   SenderThread:2039649 [sender.py:send():382] send: metric
2024-08-06 15:47:06,002 DEBUG   SenderThread:2039649 [sender.py:send():382] send: metric
2024-08-06 15:47:06,002 DEBUG   SenderThread:2039649 [sender.py:send():382] send: metric
2024-08-06 15:47:06,002 DEBUG   SenderThread:2039649 [sender.py:send():382] send: metric
2024-08-06 15:47:06,002 DEBUG   SenderThread:2039649 [sender.py:send():382] send: history
2024-08-06 15:47:06,002 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: summary_record
2024-08-06 15:47:06,002 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:47:06,194 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad
2024-08-06 15:47:06,194 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5489', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:06,194 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91418177B39C4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:06,494 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc
2024-08-06 15:47:06,494 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '13917', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:06,494 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91418255988C7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:06,714 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/wandb-summary.json
2024-08-06 15:47:07,714 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:08,714 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:08,956 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 15:47:08,957 DEBUG   SenderThread:2039649 [sender.py:send():382] send: history
2024-08-06 15:47:08,957 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: summary_record
2024-08-06 15:47:08,958 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:47:09,715 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/wandb-summary.json
2024-08-06 15:47:10,589 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=52e4398a53ca58d3cd32c395e9509295a454b0efcaaca1ad0bdda324694415ad
2024-08-06 15:47:10,589 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5489', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:10,589 ERROR   wandb-upload_0:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914191D85C1D3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:10,715 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:10,958 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 15:47:11,258 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T074702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ba1cd346e5ec3f6015881674ccc104c370a527ed7b1486ca170310eba71fa4cc
2024-08-06 15:47:11,258 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '13917', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:47:11,258 ERROR   wandb-upload_1:2039649 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/zitoe4ey/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/zitoe4ey/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E914194498586C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:47:11,715 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:11,982 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 15:47:11,983 DEBUG   SenderThread:2039649 [sender.py:send():382] send: history
2024-08-06 15:47:11,983 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: summary_record
2024-08-06 15:47:11,984 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:47:12,715 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/wandb-summary.json
2024-08-06 15:47:12,715 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:13,715 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:14,982 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 15:47:14,982 DEBUG   SenderThread:2039649 [sender.py:send():382] send: history
2024-08-06 15:47:14,982 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: summary_record
2024-08-06 15:47:14,983 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:47:15,716 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/wandb-summary.json
2024-08-06 15:47:15,983 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 15:47:16,716 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:17,534 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 15:47:17,534 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 15:47:17,535 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: stop_status
2024-08-06 15:47:17,716 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/output.log
2024-08-06 15:47:17,938 DEBUG   HandlerThread:2039649 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 15:47:17,938 DEBUG   SenderThread:2039649 [sender.py:send():382] send: history
2024-08-06 15:47:17,938 DEBUG   SenderThread:2039649 [sender.py:send_request():409] send_request: summary_record
2024-08-06 15:47:17,939 INFO    SenderThread:2039649 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:47:18,717 INFO    Thread-12 :2039649 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_154700-zitoe4ey/files/wandb-summary.json
