2024-08-08 19:48:09,946 INFO    StreamThr :338753 [internal.py:wandb_internal():86] W&B internal server running at pid: 338753, started at: 2024-08-08 19:48:09.945736
2024-08-08 19:48:09,947 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: status
2024-08-08 19:48:09,947 INFO    WriterThread:338753 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/run-lx3oyz7f.wandb
2024-08-08 19:48:09,948 DEBUG   SenderThread:338753 [sender.py:send():382] send: header
2024-08-08 19:48:09,978 DEBUG   SenderThread:338753 [sender.py:send():382] send: run
2024-08-08 19:48:10,135 INFO    SenderThread:338753 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files
2024-08-08 19:48:10,136 INFO    SenderThread:338753 [sender.py:_start_run_threads():1136] run started: lx3oyz7f with start time 1723117689.945749
2024-08-08 19:48:10,141 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 19:48:10,141 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: check_version
2024-08-08 19:48:10,232 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 19:48:10,246 DEBUG   HandlerThread:338753 [system_info.py:__init__():32] System info init
2024-08-08 19:48:10,246 DEBUG   HandlerThread:338753 [system_info.py:__init__():47] System info init done
2024-08-08 19:48:10,246 INFO    HandlerThread:338753 [system_monitor.py:start():194] Starting system monitor
2024-08-08 19:48:10,246 INFO    SystemMonitor:338753 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 19:48:10,246 INFO    HandlerThread:338753 [system_monitor.py:probe():214] Collecting system info
2024-08-08 19:48:10,247 INFO    SystemMonitor:338753 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 19:48:10,250 INFO    SystemMonitor:338753 [interfaces.py:start():190] Started disk monitoring
2024-08-08 19:48:10,251 INFO    SystemMonitor:338753 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 19:48:10,253 INFO    SystemMonitor:338753 [interfaces.py:start():190] Started memory monitoring
2024-08-08 19:48:10,254 INFO    SystemMonitor:338753 [interfaces.py:start():190] Started network monitoring
2024-08-08 19:48:10,270 DEBUG   HandlerThread:338753 [system_info.py:probe():196] Probing system
2024-08-08 19:48:10,273 DEBUG   HandlerThread:338753 [system_info.py:_probe_git():181] Probing git
2024-08-08 19:48:10,281 DEBUG   HandlerThread:338753 [system_info.py:_probe_git():189] Probing git done
2024-08-08 19:48:10,281 DEBUG   HandlerThread:338753 [system_info.py:probe():244] Probing system done
2024-08-08 19:48:10,281 DEBUG   HandlerThread:338753 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T11:48:10.270261', 'startedAt': '2024-08-08T11:48:09.941098', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--use_lora', 'True', '--init_lora_weights', 'pissa_niter_4', '--target_modules', 'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj', '--lora_rank', '32', '--lora_alpha', '32', '--lora_dropout', '0', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 939.4531071428571, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1114.031, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1130.729, 'min': 800.0, 'max': 5500.0}, {'current': 1140.467, 'min': 800.0, 'max': 5500.0}, {'current': 1101.526, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1152.535, 'min': 800.0, 'max': 5500.0}, {'current': 1134.316, 'min': 800.0, 'max': 5500.0}, {'current': 1116.859, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1126.656, 'min': 800.0, 'max': 5600.0}, {'current': 1136.097, 'min': 800.0, 'max': 5600.0}, {'current': 1124.202, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1143.297, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1100.904, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1142.05, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0432014465332}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 19:48:10,281 INFO    HandlerThread:338753 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 19:48:10,281 INFO    HandlerThread:338753 [system_monitor.py:probe():227] Publishing system info
2024-08-08 19:48:10,281 DEBUG   HandlerThread:338753 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 19:48:10,282 DEBUG   HandlerThread:338753 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 19:48:10,282 DEBUG   HandlerThread:338753 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 19:48:11,136 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/requirements.txt
2024-08-08 19:48:11,136 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/conda-environment.yaml
2024-08-08 19:48:11,963 DEBUG   HandlerThread:338753 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 19:48:11,963 DEBUG   HandlerThread:338753 [system_info.py:_save_code():90] Saving code
2024-08-08 19:48:11,964 DEBUG   HandlerThread:338753 [system_info.py:_save_code():111] Saving code done
2024-08-08 19:48:11,964 DEBUG   HandlerThread:338753 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 19:48:12,004 DEBUG   HandlerThread:338753 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 19:48:12,004 INFO    HandlerThread:338753 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 19:48:12,007 DEBUG   SenderThread:338753 [sender.py:send():382] send: files
2024-08-08 19:48:12,007 INFO    SenderThread:338753 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 19:48:12,008 INFO    SenderThread:338753 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 19:48:12,008 INFO    SenderThread:338753 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 19:48:12,015 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 19:48:12,016 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: stop_status
2024-08-08 19:48:12,018 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 19:48:12,135 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/conda-environment.yaml
2024-08-08 19:48:12,135 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/diff.patch
2024-08-08 19:48:12,135 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/code/llama/gmm.py
2024-08-08 19:48:12,136 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/wandb-metadata.json
2024-08-08 19:48:12,136 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/code/llama
2024-08-08 19:48:12,136 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/code
2024-08-08 19:48:12,260 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60
2024-08-08 19:48:12,260 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5522', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:12,260 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE695F5E0C48</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:12,274 DEBUG   SenderThread:338753 [sender.py:send():382] send: telemetry
2024-08-08 19:48:12,274 DEBUG   SenderThread:338753 [sender.py:send():382] send: config
2024-08-08 19:48:12,275 DEBUG   SenderThread:338753 [sender.py:send():382] send: metric
2024-08-08 19:48:12,275 DEBUG   SenderThread:338753 [sender.py:send():382] send: telemetry
2024-08-08 19:48:12,275 DEBUG   SenderThread:338753 [sender.py:send():382] send: metric
2024-08-08 19:48:12,275 WARNING SenderThread:338753 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 19:48:12,275 DEBUG   SenderThread:338753 [sender.py:send():382] send: telemetry
2024-08-08 19:48:12,275 DEBUG   SenderThread:338753 [sender.py:send():382] send: telemetry
2024-08-08 19:48:12,275 DEBUG   SenderThread:338753 [sender.py:send():382] send: config
2024-08-08 19:48:12,328 DEBUG   SenderThread:338753 [sender.py:send():382] send: exit
2024-08-08 19:48:12,328 INFO    SenderThread:338753 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 19:48:12,328 INFO    SenderThread:338753 [sender.py:send_exit():591] handling runtime: 2
2024-08-08 19:48:12,328 INFO    SenderThread:338753 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:48:12,328 INFO    SenderThread:338753 [sender.py:send_exit():597] send defer
2024-08-08 19:48:12,328 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,328 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 19:48:12,328 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,328 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 19:48:12,328 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 1
2024-08-08 19:48:12,328 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,329 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 19:48:12,329 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,329 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 19:48:12,329 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 2
2024-08-08 19:48:12,329 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,329 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 19:48:12,329 INFO    HandlerThread:338753 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 19:48:12,329 DEBUG   SystemMonitor:338753 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 19:48:12,329 DEBUG   SystemMonitor:338753 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 19:48:12,329 DEBUG   SystemMonitor:338753 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 19:48:12,329 INFO    HandlerThread:338753 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 19:48:12,330 INFO    HandlerThread:338753 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 19:48:12,349 INFO    HandlerThread:338753 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 19:48:12,350 INFO    HandlerThread:338753 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 19:48:12,350 INFO    HandlerThread:338753 [interfaces.py:finish():202] Joined network monitor
2024-08-08 19:48:12,350 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 3
2024-08-08 19:48:12,350 DEBUG   SenderThread:338753 [sender.py:send():382] send: stats
2024-08-08 19:48:12,350 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,350 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 19:48:12,350 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 4
2024-08-08 19:48:12,350 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,350 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 19:48:12,350 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 5
2024-08-08 19:48:12,350 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,350 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 19:48:12,350 DEBUG   SenderThread:338753 [sender.py:send():382] send: summary
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:48:12,350 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 19:48:12,350 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 6
2024-08-08 19:48:12,350 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,350 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 19:48:12,351 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,351 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 19:48:12,352 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 19:48:12,419 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff
2024-08-08 19:48:12,419 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:12,419 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE6962B6FF8F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:12,889 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 7
2024-08-08 19:48:12,889 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:12,889 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 19:48:12,889 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:12,889 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 19:48:13,136 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/config.yaml
2024-08-08 19:48:13,137 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/wandb-summary.json
2024-08-08 19:48:13,137 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/output.log
2024-08-08 19:48:13,326 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 19:48:13,451 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=26dbcc2e2343522eead3fa145eb2103cafe4e5ce9fda64a6e349cc53ef296cd7: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=26dbcc2e2343522eead3fa145eb2103cafe4e5ce9fda64a6e349cc53ef296cd7
2024-08-08 19:48:13,451 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293138', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:13,451 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE6966F5D385</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:13,553 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60
2024-08-08 19:48:13,553 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5522', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:13,553 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE69AC837162</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:13,553 INFO    wandb-upload_0:338753 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:48:13,591 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff
2024-08-08 19:48:13,591 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:13,591 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE69AD65D92E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:13,592 INFO    wandb-upload_1:338753 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:48:14,290 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 8
2024-08-08 19:48:14,290 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 19:48:14,291 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:14,291 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 19:48:14,291 DEBUG   SenderThread:338753 [sender.py:send_request():409] send_request: defer
2024-08-08 19:48:14,291 INFO    SenderThread:338753 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 19:48:14,291 INFO    SenderThread:338753 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 19:48:14,291 INFO    SenderThread:338753 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 19:48:14,304 INFO    SenderThread:338753 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 19:48:14,316 INFO    SenderThread:338753 [sender.py:transition_state():617] send defer: 9
2024-08-08 19:48:14,316 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:48:14,316 INFO    HandlerThread:338753 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 19:48:14,317 DEBUG   SenderThread:338753 [sender.py:send():382] send: artifact
2024-08-08 19:48:14,327 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 19:48:15,137 INFO    Thread-12 :338753 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194809-lx3oyz7f/files/output.log
2024-08-08 19:48:15,335 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=26dbcc2e2343522eead3fa145eb2103cafe4e5ce9fda64a6e349cc53ef296cd7: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=26dbcc2e2343522eead3fa145eb2103cafe4e5ce9fda64a6e349cc53ef296cd7
2024-08-08 19:48:15,335 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293138', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:15,335 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE69EEDDA368</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:15,420 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36
2024-08-08 19:48:15,420 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:15,420 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE6A1BC6AD4D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:15,629 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e
2024-08-08 19:48:15,629 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:15,629 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE6A1F2B6035</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:16,023 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60
2024-08-08 19:48:16,024 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5522', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:16,024 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE6A3FB871F6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:16,163 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff
2024-08-08 19:48:16,163 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:16,163 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE6A30AE8984</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:16,593 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36
2024-08-08 19:48:16,593 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:16,593 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE6A61C65BD4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:16,988 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e
2024-08-08 19:48:16,988 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:16,988 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE6A74600DDA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:18,098 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=26dbcc2e2343522eead3fa145eb2103cafe4e5ce9fda64a6e349cc53ef296cd7: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=26dbcc2e2343522eead3fa145eb2103cafe4e5ce9fda64a6e349cc53ef296cd7
2024-08-08 19:48:18,099 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293138', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:18,099 ERROR   wandb-upload_2:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE6AA890FEEE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:19,042 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36
2024-08-08 19:48:19,042 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:19,042 ERROR   wandb-upload_3:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE6AF384FEC8</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:19,042 INFO    wandb-upload_3:338753 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=3aef0c1149484f6a9c27f2aaac28767f81d372448053229e4fa3c5368eb18b36

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:48:19,329 DEBUG   HandlerThread:338753 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:48:19,538 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e
2024-08-08 19:48:19,538 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:19,538 ERROR   wandb-upload_4:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE6B0F69EEB2</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:19,538 INFO    wandb-upload_4:338753 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/531/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114815Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d7c63b6b72c712afdf5ec05f930f941acdbac7de98d7779dd1117689200e904e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:48:20,596 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=443c934291f20cd0d80730218609efccebb8fa27125876d302d752686388bc60
2024-08-08 19:48:20,596 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5522', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:20,596 ERROR   wandb-upload_0:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE6B4FEA6C7D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:48:21,002 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114812Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e3020533e95ebbf919847c0e6f0f4a85e52716f7e4ada61cad768d20102680ff
2024-08-08 19:48:21,002 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:48:21,002 ERROR   wandb-upload_1:338753 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lx3oyz7f/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE6B67686D32</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
